# This file has been generated by node2nix 1.0.0. Do not edit!

{nodeEnv, fetchurl, fetchgit}:

let
  sources = {
    "grunt-0.4.5" = {
      name = "grunt";
      packageName = "grunt";
      version = "0.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz";
        sha1 = "56937cd5194324adff6d207631832a9d6ba4e7f0";
      };
    };
    "grunt-contrib-copy-1.0.0" = {
      name = "grunt-contrib-copy";
      packageName = "grunt-contrib-copy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-copy/-/grunt-contrib-copy-1.0.0.tgz";
        sha1 = "7060c6581e904b8ab0d00f076e0a8f6e3e7c3573";
      };
    };
    "grunt-contrib-concat-0.5.1" = {
      name = "grunt-contrib-concat";
      packageName = "grunt-contrib-concat";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-concat/-/grunt-contrib-concat-0.5.1.tgz";
        sha1 = "953c6efdfdfd2c107ab9c85077f2d4b24d31cd49";
      };
    };
    "grunt-contrib-jshint-0.12.0" = {
      name = "grunt-contrib-jshint";
      packageName = "grunt-contrib-jshint";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-jshint/-/grunt-contrib-jshint-0.12.0.tgz";
        sha1 = "f6b2f06fc715264837a7ab6c69a1ce1a689c2c29";
      };
    };
    "grunt-contrib-less-1.4.1" = {
      name = "grunt-contrib-less";
      packageName = "grunt-contrib-less";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-less/-/grunt-contrib-less-1.4.1.tgz";
        sha1 = "3bbdec0b75d12ceaa55d62943625c0b0861cdf6f";
      };
    };
    "grunt-contrib-watch-0.6.1" = {
      name = "grunt-contrib-watch";
      packageName = "grunt-contrib-watch";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-watch/-/grunt-contrib-watch-0.6.1.tgz";
        sha1 = "64fdcba25a635f5b4da1b6ce6f90da0aeb6e3f15";
      };
    };
    "crisper-2.1.1" = {
      name = "crisper";
      packageName = "crisper";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/crisper/-/crisper-2.1.1.tgz";
        sha1 = "4cc7321c3e90f3c5cbdc3503217f118fd7d5c51c";
      };
    };
    "vulcanize-1.16.0" = {
      name = "vulcanize";
      packageName = "vulcanize";
      version = "1.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vulcanize/-/vulcanize-1.16.0.tgz";
        sha1 = "b0ce3b0044d194ad4908ae4f1a6c6110a6e4d5e6";
      };
    };
    "grunt-crisper-1.0.1" = {
      name = "grunt-crisper";
      packageName = "grunt-crisper";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-crisper/-/grunt-crisper-1.0.1.tgz";
        sha1 = "e7c091dcaff10deb0091e3035ca7e54008991fe7";
      };
    };
    "grunt-vulcanize-1.0.0" = {
      name = "grunt-vulcanize";
      packageName = "grunt-vulcanize";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-vulcanize/-/grunt-vulcanize-1.0.0.tgz";
        sha1 = "f4d6cfef274f8216c06f6c290e7dbb3b9e9e3b0f";
      };
    };
    "node2nix-1.3.0" = {
      name = "node2nix";
      packageName = "node2nix";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node2nix/-/node2nix-1.3.0.tgz";
        sha1 = "e830a3bc5880dd22ae47be71a147f776542850cc";
      };
    };
    "jshint-2.9.5" = {
      name = "jshint";
      packageName = "jshint";
      version = "2.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jshint/-/jshint-2.9.5.tgz";
        sha1 = "1e7252915ce681b40827ee14248c46d34e9aa62c";
      };
    };
    "bower-1.8.2" = {
      name = "bower";
      packageName = "bower";
      version = "1.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bower/-/bower-1.8.2.tgz";
        sha1 = "adf53529c8d4af02ef24fb8d5341c1419d33e2f7";
      };
    };
    "jquery-1.11.3" = {
      name = "jquery";
      packageName = "jquery";
      version = "1.11.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-1.11.3.tgz";
        sha1 = "dd8b74278b27102d29df63eae28308a8cfa1b583";
      };
    };
    "favico.js-0.3.10" = {
      name = "favico.js";
      packageName = "favico.js";
      version = "0.3.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/favico.js/-/favico.js-0.3.10.tgz";
        sha1 = "80586e27a117f24a8d51c18a99bdc714d4339301";
      };
    };
    "clipboard-1.7.1" = {
      name = "clipboard";
      packageName = "clipboard";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clipboard/-/clipboard-1.7.1.tgz";
        sha1 = "360d6d6946e99a7a1fef395e42ba92b5e9b5a16b";
      };
    };
    "moment-2.18.1" = {
      name = "moment";
      packageName = "moment";
      version = "2.18.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.18.1.tgz";
        sha1 = "c36193dd3ce1c2eed2adb7c802dbbc77a81b1c0f";
      };
    };
    "mousetrap-1.6.1" = {
      name = "mousetrap";
      packageName = "mousetrap";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mousetrap/-/mousetrap-1.6.1.tgz";
        sha1 = "2a085f5c751294c75e7e81f6ec2545b29cbf42d9";
      };
    };
    "appenlight-client-git+https://git@github.com/AppEnlight/appenlight-client-js.git#0.5.1" = {
      name = "appenlight-client";
      packageName = "appenlight-client";
      version = "0.5.1";
      src = fetchgit {
        url = "https://git@github.com/AppEnlight/appenlight-client-js.git";
        rev = "14712c64c230fbbe94fcbc8094aef5eb3b90b307";
        sha256 = "92111f1104cbf0b31303c366c0fa752cf68af7ddde40d0161edd1b5fd9dd07f7";
      };
    };
    "async-0.1.22" = {
      name = "async";
      packageName = "async";
      version = "0.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.1.22.tgz";
        sha1 = "0fc1aaa088a0e3ef0ebe2d8831bab0dcf8845061";
      };
    };
    "coffee-script-1.3.3" = {
      name = "coffee-script";
      packageName = "coffee-script";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/coffee-script/-/coffee-script-1.3.3.tgz";
        sha1 = "150d6b4cb522894369efed6a2101c20bc7f4a4f4";
      };
    };
    "colors-0.6.2" = {
      name = "colors";
      packageName = "colors";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-0.6.2.tgz";
        sha1 = "2423fe6678ac0c5dae8852e5d0e5be08c997abcc";
      };
    };
    "dateformat-1.0.2-1.2.3" = {
      name = "dateformat";
      packageName = "dateformat";
      version = "1.0.2-1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dateformat/-/dateformat-1.0.2-1.2.3.tgz";
        sha1 = "b0220c02de98617433b72851cf47de3df2cdbee9";
      };
    };
    "eventemitter2-0.4.14" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "0.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.14.tgz";
        sha1 = "8f61b75cde012b2e9eb284d4545583b5643b61ab";
      };
    };
    "findup-sync-0.1.3" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-0.1.3.tgz";
        sha1 = "7f3e7a97b82392c653bf06589bd85190e93c3683";
      };
    };
    "glob-3.1.21" = {
      name = "glob";
      packageName = "glob";
      version = "3.1.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-3.1.21.tgz";
        sha1 = "d29e0a055dea5138f4d07ed40e8982e83c2066cd";
      };
    };
    "hooker-0.2.3" = {
      name = "hooker";
      packageName = "hooker";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hooker/-/hooker-0.2.3.tgz";
        sha1 = "b834f723cc4a242aa65963459df6d984c5d3d959";
      };
    };
    "iconv-lite-0.2.11" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.2.11.tgz";
        sha1 = "1ce60a3a57864a292d1321ff4609ca4bb965adc8";
      };
    };
    "minimatch-0.2.14" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "0.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-0.2.14.tgz";
        sha1 = "c74e780574f63c6f9a090e90efbe6ef53a6a756a";
      };
    };
    "nopt-1.0.10" = {
      name = "nopt";
      packageName = "nopt";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-1.0.10.tgz";
        sha1 = "6ddd21bd2a31417b92727dd585f8a6f37608ebee";
      };
    };
    "rimraf-2.2.8" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz";
        sha1 = "e439be2aaee327321952730f99a8929e4fc50582";
      };
    };
    "lodash-0.9.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-0.9.2.tgz";
        sha1 = "8f3499c5245d346d682e5b0d3b40767e09f1a92c";
      };
    };
    "underscore.string-2.2.1" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.2.1.tgz";
        sha1 = "d7c0fa2af5d5a1a67f4253daee98132e733f0f19";
      };
    };
    "which-1.0.9" = {
      name = "which";
      packageName = "which";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.0.9.tgz";
        sha1 = "460c1da0f810103d0321a9b633af9e575e64486f";
      };
    };
    "js-yaml-2.0.5" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-2.0.5.tgz";
        sha1 = "a25ae6509999e97df278c6719da11bd0687743a8";
      };
    };
    "exit-0.1.2" = {
      name = "exit";
      packageName = "exit";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit/-/exit-0.1.2.tgz";
        sha1 = "0632638f8d877cc82107d30a0fff1a17cba1cd0c";
      };
    };
    "getobject-0.1.0" = {
      name = "getobject";
      packageName = "getobject";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/getobject/-/getobject-0.1.0.tgz";
        sha1 = "047a449789fa160d018f5486ed91320b6ec7885c";
      };
    };
    "grunt-legacy-util-0.2.0" = {
      name = "grunt-legacy-util";
      packageName = "grunt-legacy-util";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-util/-/grunt-legacy-util-0.2.0.tgz";
        sha1 = "93324884dbf7e37a9ff7c026dff451d94a9e554b";
      };
    };
    "grunt-legacy-log-0.1.3" = {
      name = "grunt-legacy-log";
      packageName = "grunt-legacy-log";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log/-/grunt-legacy-log-0.1.3.tgz";
        sha1 = "ec29426e803021af59029f87d2f9cd7335a05531";
      };
    };
    "glob-3.2.11" = {
      name = "glob";
      packageName = "glob";
      version = "3.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-3.2.11.tgz";
        sha1 = "4a973f635b9190f715d10987d5c00fd2815ebe3d";
      };
    };
    "lodash-2.4.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz";
        sha1 = "fadd834b9683073da179b3eae6d9c0d15053f73e";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "minimatch-0.3.0" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz";
        sha1 = "275d8edaac4f1bb3326472089e7949c8394699dd";
      };
    };
    "lru-cache-2.7.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz";
        sha1 = "6d4524e8b955f95d4f5b58851ce21dd72fb4e952";
      };
    };
    "sigmund-1.0.1" = {
      name = "sigmund";
      packageName = "sigmund";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz";
        sha1 = "3ff21f198cad2175f9f3b781853fd94d0d19b590";
      };
    };
    "graceful-fs-1.2.3" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-1.2.3.tgz";
        sha1 = "15a4806a57547cb2d2dbf27f42e89a8c3451b364";
      };
    };
    "inherits-1.0.2" = {
      name = "inherits";
      packageName = "inherits";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-1.0.2.tgz";
        sha1 = "ca4309dadee6b54cc0b8d247e8d7c7a0975bdc9b";
      };
    };
    "abbrev-1.1.0" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.0.tgz";
        sha1 = "d0554c2256636e2f56e7c2e5ad183f859428d81f";
      };
    };
    "argparse-0.1.16" = {
      name = "argparse";
      packageName = "argparse";
      version = "0.1.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-0.1.16.tgz";
        sha1 = "cfd01e0fbba3d6caed049fbd758d40f65196f57c";
      };
    };
    "esprima-1.0.4" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz";
        sha1 = "9f557e08fc3b4d26ece9dd34f8fbf476b62585ad";
      };
    };
    "underscore-1.7.0" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz";
        sha1 = "6bbaf0877500d36be34ecaa584e0db9fef035209";
      };
    };
    "underscore.string-2.4.0" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.4.0.tgz";
        sha1 = "8cdd8fbac4e2d2ea1e7e2e8097c42f442280f85b";
      };
    };
    "grunt-legacy-log-utils-0.1.1" = {
      name = "grunt-legacy-log-utils";
      packageName = "grunt-legacy-log-utils";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log-utils/-/grunt-legacy-log-utils-0.1.1.tgz";
        sha1 = "c0706b9dd9064e116f36f23fe4e6b048672c0f7e";
      };
    };
    "underscore.string-2.3.3" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.3.3.tgz";
        sha1 = "71c08bf6b428b1133f37e78fa3a21c82f7329b0d";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "file-sync-cmp-0.1.1" = {
      name = "file-sync-cmp";
      packageName = "file-sync-cmp";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-sync-cmp/-/file-sync-cmp-0.1.1.tgz";
        sha1 = "a5e7a8ffbfa493b43b923bbd4ca89a53b63b612b";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "chalk-0.5.1" = {
      name = "chalk";
      packageName = "chalk";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-0.5.1.tgz";
        sha1 = "663b3a648b68b55d04690d49167aa837858f2174";
      };
    };
    "source-map-0.3.0" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.3.0.tgz";
        sha1 = "8586fb9a5a005e5b501e21cd18b6f21b457ad1f9";
      };
    };
    "ansi-styles-1.1.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-1.1.0.tgz";
        sha1 = "eaecbf66cd706882760b2f4691582b8f55d7a7de";
      };
    };
    "has-ansi-0.1.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-0.1.0.tgz";
        sha1 = "84f265aae8c0e6a88a12d7022894b7568894c62e";
      };
    };
    "strip-ansi-0.3.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-0.3.0.tgz";
        sha1 = "25f48ea22ca79187f3174a4db8759347bb126220";
      };
    };
    "supports-color-0.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-0.2.0.tgz";
        sha1 = "d92de2694eb3f67323973d7ae3d8b55b4c22190a";
      };
    };
    "ansi-regex-0.2.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-0.2.1.tgz";
        sha1 = "0d8e946967a3d8143f93e24e298525fc1b2235f9";
      };
    };
    "amdefine-1.0.1" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.1.tgz";
        sha1 = "4a5282ac164729e93619bcfd3ad151f817ce91f5";
      };
    };
    "async-2.5.0" = {
      name = "async";
      packageName = "async";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.5.0.tgz";
        sha1 = "843190fd6b7357a0b9e1c956edddd5ec8462b54d";
      };
    };
    "less-2.7.2" = {
      name = "less";
      packageName = "less";
      version = "2.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/less/-/less-2.7.2.tgz";
        sha1 = "368d6cc73e1fb03981183280918743c5dcf9b3df";
      };
    };
    "lodash-4.17.4" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.4.tgz";
        sha1 = "78203a4d1c328ae1d86dca6460e369b57f4055ae";
      };
    };
    "errno-0.1.4" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.4.tgz";
        sha1 = "b896e23a9e5e8ba33871fc996abd3635fc9a1c7d";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "image-size-0.5.5" = {
      name = "image-size";
      packageName = "image-size";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-size/-/image-size-0.5.5.tgz";
        sha1 = "09dfd4ab9d20e29eb1c3e80b8990378df9e3cb9c";
      };
    };
    "mime-1.4.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.4.0.tgz";
        sha1 = "69e9e0db51d44f2a3b56e48b7817d7d137f1a343";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "promise-7.3.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.3.1.tgz";
        sha1 = "064b72602b18f90f29192b8b1bc418ffd1ebd3bf";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha1 = "8a039d2d1021d22d1ea14c80d8ea468ba2ef3fcc";
      };
    };
    "request-2.82.0" = {
      name = "request";
      packageName = "request";
      version = "2.82.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.82.0.tgz";
        sha1 = "2ba8a92cd7ac45660ea2b10a53ae67cd247516ea";
      };
    };
    "prr-0.0.0" = {
      name = "prr";
      packageName = "prr";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-0.0.0.tgz";
        sha1 = "1a84b85908325501411853d0081ee3fa86e2926a";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.1" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.1.tgz";
        sha1 = "6fb94fbd71885306d73d15cc497fe4cc4ecd44bf";
      };
    };
    "har-validator-5.0.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.0.3.tgz";
        sha1 = "ba402c266194f15956ef15e0fcf242993f6a7dfd";
      };
    };
    "hawk-6.0.2" = {
      name = "hawk";
      packageName = "hawk";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-6.0.2.tgz";
        sha1 = "af4d914eb065f9b5ce4d9d11c1cb2126eecc3038";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.17" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz";
        sha1 = "09d7a393f03e995a79f8af857b70a9e0ab16557a";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "qs-6.5.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.1.tgz";
        sha1 = "349cdf6eef89ec45c12d7d5eb3fc0c870343a6d8";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha1 = "893312af69b2123def71f57889001671eeb2c853";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.3" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.3.tgz";
        sha1 = "0b618a5565b6dea90bf3425d04d55edc475a7561";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "uuid-3.1.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.1.0.tgz";
        sha1 = "3dd3d3e790abc24d7b0d3a034ffababe28ebbc04";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "ajv-5.2.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.2.2.tgz";
        sha1 = "47c68d69e86f5d953103b0074a9430dc63da5e39";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "fast-deep-equal-1.0.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.0.0.tgz";
        sha1 = "96256a3bc975595eb36d82e9929d060d893439ff";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "json-stable-stringify-1.0.1" = {
      name = "json-stable-stringify";
      packageName = "json-stable-stringify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify/-/json-stable-stringify-1.0.1.tgz";
        sha1 = "9a759d39c5f2ff503fd5300646ed445f88c4f9af";
      };
    };
    "jsonify-0.0.0" = {
      name = "jsonify";
      packageName = "jsonify";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonify/-/jsonify-0.0.0.tgz";
        sha1 = "2c74b6ee41d93ca51b7b5aaee8f503631d252a73";
      };
    };
    "hoek-4.2.0" = {
      name = "hoek";
      packageName = "hoek";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-4.2.0.tgz";
        sha1 = "72d9d0754f7fe25ca2d01ad8f8f9a9449a89526d";
      };
    };
    "boom-4.3.1" = {
      name = "boom";
      packageName = "boom";
      version = "4.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-4.3.1.tgz";
        sha1 = "4f8a3005cb4a7e3889f749030fd25b96e01d2e31";
      };
    };
    "cryptiles-3.1.2" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-3.1.2.tgz";
        sha1 = "a89fbb220f5ce25ec56e8c4aa8a4fd7b5b0d29fe";
      };
    };
    "sntp-2.0.2" = {
      name = "sntp";
      packageName = "sntp";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-2.0.2.tgz";
        sha1 = "5064110f0af85f7cfdb7d6b67a40028ce52b4b2b";
      };
    };
    "boom-5.2.0" = {
      name = "boom";
      packageName = "boom";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-5.2.0.tgz";
        sha1 = "5dd9da6ee3a5f302077436290cb717d3f4a54e02";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "sshpk-1.13.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.1.tgz";
        sha1 = "512df6da6287144316dc4c18fe1cf1d940739be3";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "mime-db-1.30.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz";
        sha1 = "74c643da2dd9d6a45399963465b26d5ca7d71f01";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "gaze-0.5.2" = {
      name = "gaze";
      packageName = "gaze";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gaze/-/gaze-0.5.2.tgz";
        sha1 = "40b709537d24d1d45767db5a908689dfe69ac44f";
      };
    };
    "tiny-lr-fork-0.0.5" = {
      name = "tiny-lr-fork";
      packageName = "tiny-lr-fork";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-lr-fork/-/tiny-lr-fork-0.0.5.tgz";
        sha1 = "1e99e1e2a8469b736ab97d97eefa98c71f76ed0a";
      };
    };
    "async-0.2.10" = {
      name = "async";
      packageName = "async";
      version = "0.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.2.10.tgz";
        sha1 = "b6bbe0b0674b9d719708ca38de8c237cb526c3d1";
      };
    };
    "globule-0.1.0" = {
      name = "globule";
      packageName = "globule";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globule/-/globule-0.1.0.tgz";
        sha1 = "d9c8edde1da79d125a151b79533b978676346ae5";
      };
    };
    "lodash-1.0.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-1.0.2.tgz";
        sha1 = "8f57560c83b59fc270bd3d561b690043430e2551";
      };
    };
    "qs-0.5.6" = {
      name = "qs";
      packageName = "qs";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-0.5.6.tgz";
        sha1 = "31b1ad058567651c526921506b9a8793911a0384";
      };
    };
    "faye-websocket-0.4.4" = {
      name = "faye-websocket";
      packageName = "faye-websocket";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.4.4.tgz";
        sha1 = "c14c5b3bf14d7417ffbfd990c0a7495cd9f337bc";
      };
    };
    "noptify-0.0.3" = {
      name = "noptify";
      packageName = "noptify";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/noptify/-/noptify-0.0.3.tgz";
        sha1 = "58f654a73d9753df0c51d9686dc92104a67f4bbb";
      };
    };
    "debug-0.7.4" = {
      name = "debug";
      packageName = "debug";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-0.7.4.tgz";
        sha1 = "06e1ea8082c2cb14e39806e22e2f6f757f92af39";
      };
    };
    "nopt-2.0.0" = {
      name = "nopt";
      packageName = "nopt";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-2.0.0.tgz";
        sha1 = "ca7416f20a5e3f9c3b86180f96295fa3d0b52e0d";
      };
    };
    "command-line-args-3.0.5" = {
      name = "command-line-args";
      packageName = "command-line-args";
      version = "3.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-args/-/command-line-args-3.0.5.tgz";
        sha1 = "5bd4ad45e7983e5c1344918e40280ee2693c5ac0";
      };
    };
    "command-line-usage-3.0.8" = {
      name = "command-line-usage";
      packageName = "command-line-usage";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-usage/-/command-line-usage-3.0.8.tgz";
        sha1 = "b6a20978c1b383477f5c11a529428b880bfe0f4d";
      };
    };
    "dom5-1.3.6" = {
      name = "dom5";
      packageName = "dom5";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom5/-/dom5-1.3.6.tgz";
        sha1 = "a7088a9fc5f3b08dc9f6eda4c7abaeb241945e0d";
      };
    };
    "array-back-1.0.4" = {
      name = "array-back";
      packageName = "array-back";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-back/-/array-back-1.0.4.tgz";
        sha1 = "644ba7f095f7ffcf7c43b5f0dc39d3c1f03c063b";
      };
    };
    "feature-detect-es6-1.3.1" = {
      name = "feature-detect-es6";
      packageName = "feature-detect-es6";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/feature-detect-es6/-/feature-detect-es6-1.3.1.tgz";
        sha1 = "f888736af9cb0c91f55663bfa4762eb96ee7047f";
      };
    };
    "find-replace-1.0.3" = {
      name = "find-replace";
      packageName = "find-replace";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-replace/-/find-replace-1.0.3.tgz";
        sha1 = "b88e7364d2d9c959559f388c66670d6130441fa0";
      };
    };
    "typical-2.6.1" = {
      name = "typical";
      packageName = "typical";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/typical/-/typical-2.6.1.tgz";
        sha1 = "5c080e5d661cbbe38259d2e70a3c7253e873881d";
      };
    };
    "test-value-2.1.0" = {
      name = "test-value";
      packageName = "test-value";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/test-value/-/test-value-2.1.0.tgz";
        sha1 = "11da6ff670f3471a73b625ca4f3fdcf7bb748291";
      };
    };
    "ansi-escape-sequences-3.0.0" = {
      name = "ansi-escape-sequences";
      packageName = "ansi-escape-sequences";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escape-sequences/-/ansi-escape-sequences-3.0.0.tgz";
        sha1 = "1c18394b6af9b76ff9a63509fa497669fd2ce53e";
      };
    };
    "table-layout-0.3.0" = {
      name = "table-layout";
      packageName = "table-layout";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/table-layout/-/table-layout-0.3.0.tgz";
        sha1 = "6ee20dc483db371b3e5c87f704ed2f7c799d2c9a";
      };
    };
    "core-js-2.5.1" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.5.1.tgz";
        sha1 = "ae6874dc66937789b80754ff5428df66819ca50b";
      };
    };
    "deep-extend-0.4.2" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.4.2.tgz";
        sha1 = "48b699c27e334bf89f10892be432f6e4c7d34a7f";
      };
    };
    "wordwrapjs-2.0.0" = {
      name = "wordwrapjs";
      packageName = "wordwrapjs";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrapjs/-/wordwrapjs-2.0.0.tgz";
        sha1 = "ab55f695e6118da93858fdd70c053d1c5e01ac20";
      };
    };
    "reduce-flatten-1.0.1" = {
      name = "reduce-flatten";
      packageName = "reduce-flatten";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/reduce-flatten/-/reduce-flatten-1.0.1.tgz";
        sha1 = "258c78efd153ddf93cb561237f61184f3696e327";
      };
    };
    "@types/clone-0.1.30" = {
      name = "@types/clone";
      packageName = "@types/clone";
      version = "0.1.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/clone/-/clone-0.1.30.tgz";
        sha1 = "e7365648c1b42136a59c7d5040637b3b5c83b614";
      };
    };
    "@types/node-4.2.20" = {
      name = "@types/node";
      packageName = "@types/node";
      version = "4.2.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-4.2.20.tgz";
        sha1 = "3f7dceff43e07cfff4407fc3495d98a533b32267";
      };
    };
    "@types/parse5-0.0.31" = {
      name = "@types/parse5";
      packageName = "@types/parse5";
      version = "0.0.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/parse5/-/parse5-0.0.31.tgz";
        sha1 = "e827a493a443b156e1b582a2e4c3bdc0040f2ee7";
      };
    };
    "clone-1.0.2" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.2.tgz";
        sha1 = "260b7a99ebb1edfe247538175f783243cb19d149";
      };
    };
    "parse5-1.5.1" = {
      name = "parse5";
      packageName = "parse5";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse5/-/parse5-1.5.1.tgz";
        sha1 = "9b7f3b0de32be78dc2401b17573ccaf0f6f59d94";
      };
    };
    "@types/node-6.0.88" = {
      name = "@types/node";
      packageName = "@types/node";
      version = "6.0.88";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-6.0.88.tgz";
        sha1 = "f618f11a944f6a18d92b5c472028728a3e3d4b66";
      };
    };
    "es6-promise-2.3.0" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-2.3.0.tgz";
        sha1 = "96edb9f2fdb01995822b263dd8aadab6748181bc";
      };
    };
    "hydrolysis-1.25.0" = {
      name = "hydrolysis";
      packageName = "hydrolysis";
      version = "1.25.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hydrolysis/-/hydrolysis-1.25.0.tgz";
        sha1 = "a4fb14a37a1e03b0db52d8aaa57c682272a14d84";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "path-posix-1.0.0" = {
      name = "path-posix";
      packageName = "path-posix";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-posix/-/path-posix-1.0.0.tgz";
        sha1 = "06b26113f56beab042545a23bfa88003ccac260f";
      };
    };
    "acorn-3.3.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-3.3.0.tgz";
        sha1 = "45e37fb39e8da3f25baee3ff5369e2bb5f22017a";
      };
    };
    "babel-polyfill-6.26.0" = {
      name = "babel-polyfill";
      packageName = "babel-polyfill";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-polyfill/-/babel-polyfill-6.26.0.tgz";
        sha1 = "379937abc67d7895970adc621f284cd966cf2153";
      };
    };
    "doctrine-0.7.2" = {
      name = "doctrine";
      packageName = "doctrine";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctrine/-/doctrine-0.7.2.tgz";
        sha1 = "7cb860359ba3be90e040b26b729ce4bfa654c523";
      };
    };
    "dom5-1.1.0" = {
      name = "dom5";
      packageName = "dom5";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom5/-/dom5-1.1.0.tgz";
        sha1 = "3a0c7700c083ab4c4d26938a78b0f0c6dcc37794";
      };
    };
    "escodegen-1.9.0" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.9.0.tgz";
        sha1 = "9811a2f265dc1cd3894420ee3717064b632b8852";
      };
    };
    "espree-3.5.1" = {
      name = "espree";
      packageName = "espree";
      version = "3.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-3.5.1.tgz";
        sha1 = "0c988b8ab46db53100a1954ae4ba995ddd27d87e";
      };
    };
    "estraverse-3.1.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-3.1.0.tgz";
        sha1 = "15e28a446b8b82bc700ccc8b96c78af4da0d6cba";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "babel-runtime-6.26.0" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz";
        sha1 = "965c7058668e82b55d7bfe04ff2337bc8b5647fe";
      };
    };
    "regenerator-runtime-0.10.5" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.10.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.10.5.tgz";
        sha1 = "336c3efc1220adcedda2c9fab67b5a7955a33658";
      };
    };
    "regenerator-runtime-0.11.0" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.11.0.tgz";
        sha1 = "7e54fe5b5ccd5d6624ea6255c3473be090b802e1";
      };
    };
    "esutils-1.1.6" = {
      name = "esutils";
      packageName = "esutils";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-1.1.6.tgz";
        sha1 = "c01ccaa9ae4b897c6d0c3e210ae52f3c7a844375";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "estraverse-4.2.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.2.0.tgz";
        sha1 = "0dee3fed31fcd469618ce7342099fc1afa0bdb13";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "esprima-3.1.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.1.3.tgz";
        sha1 = "fdca51cee6133895e3c88d535ce49dbff62a4633";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "acorn-5.1.2" = {
      name = "acorn";
      packageName = "acorn";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-5.1.2.tgz";
        sha1 = "911cb53e036807cf0fa778dc5d370fbd864246d7";
      };
    };
    "acorn-jsx-3.0.1" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-3.0.1.tgz";
        sha1 = "afdf9488fb1ecefc8348f6fb22f464e32a58b36b";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "crisper-1.2.0" = {
      name = "crisper";
      packageName = "crisper";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crisper/-/crisper-1.2.0.tgz";
        sha1 = "9a91f597d71f6110294e076ad44dbb3408568e46";
      };
    };
    "optparse-1.0.5" = {
      name = "optparse";
      packageName = "optparse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/optparse/-/optparse-1.0.5.tgz";
        sha1 = "75e75a96506611eb1c65ba89018ff08a981e2c16";
      };
    };
    "semver-5.4.1" = {
      name = "semver";
      packageName = "semver";
      version = "5.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.4.1.tgz";
        sha1 = "e059c09d8571f0540823733433505d3a2f00b18e";
      };
    };
    "npm-registry-client-8.4.0" = {
      name = "npm-registry-client";
      packageName = "npm-registry-client";
      version = "8.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-registry-client/-/npm-registry-client-8.4.0.tgz";
        sha1 = "d52b901685647fc62a4c03eafecb6ceaa5018d4c";
      };
    };
    "npmconf-2.1.2" = {
      name = "npmconf";
      packageName = "npmconf";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmconf/-/npmconf-2.1.2.tgz";
        sha1 = "66606a4a736f1e77a059aa071a79c94ab781853a";
      };
    };
    "tar-3.1.15" = {
      name = "tar";
      packageName = "tar";
      version = "3.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-3.1.15.tgz";
        sha1 = "cccdc35b90917d58e4c3837795d5d022d7a1f46f";
      };
    };
    "temp-0.8.3" = {
      name = "temp";
      packageName = "temp";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/temp/-/temp-0.8.3.tgz";
        sha1 = "e0c6bc4d26b903124410e4fed81103014dfc1f59";
      };
    };
    "fs.extra-1.3.2" = {
      name = "fs.extra";
      packageName = "fs.extra";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.extra/-/fs.extra-1.3.2.tgz";
        sha1 = "dd023f93013bee24531f1b33514c37b20fd93349";
      };
    };
    "findit-2.0.0" = {
      name = "findit";
      packageName = "findit";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/findit/-/findit-2.0.0.tgz";
        sha1 = "6509f0126af4c178551cfa99394e032e13a4d56e";
      };
    };
    "base64-js-1.2.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.2.1.tgz";
        sha1 = "a91947da1f4a516ea38e5b4ec0ec3773675e0886";
      };
    };
    "slasp-0.0.4" = {
      name = "slasp";
      packageName = "slasp";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/slasp/-/slasp-0.0.4.tgz";
        sha1 = "9adc26ee729a0f95095851a5489f87a5258d57a9";
      };
    };
    "nijs-0.0.23" = {
      name = "nijs";
      packageName = "nijs";
      version = "0.0.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/nijs/-/nijs-0.0.23.tgz";
        sha1 = "dbf8f4a0acafbe3b8d9b71c24cbd1d851de6c31a";
      };
    };
    "concat-stream-1.6.0" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.0.tgz";
        sha1 = "0aac662fd52be78964d5532f694784e70110acf7";
      };
    };
    "normalize-package-data-2.4.0" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.4.0.tgz";
        sha1 = "12f95a307d58352075a04907b84ac8be98ac012f";
      };
    };
    "npm-package-arg-5.1.2" = {
      name = "npm-package-arg";
      packageName = "npm-package-arg";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-package-arg/-/npm-package-arg-5.1.2.tgz";
        sha1 = "fb18d17bb61e60900d6312619919bd753755ab37";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "retry-0.10.1" = {
      name = "retry";
      packageName = "retry";
      version = "0.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/retry/-/retry-0.10.1.tgz";
        sha1 = "e76388d217992c252750241d3d3956fed98d8ff4";
      };
    };
    "slide-1.1.6" = {
      name = "slide";
      packageName = "slide";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/slide/-/slide-1.1.6.tgz";
        sha1 = "56eb027d65b4d2dce6cb2e2d32c4d4afc9e1d707";
      };
    };
    "ssri-4.1.6" = {
      name = "ssri";
      packageName = "ssri";
      version = "4.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ssri/-/ssri-4.1.6.tgz";
        sha1 = "0cb49b6ac84457e7bdd466cb730c3cb623e9a25b";
      };
    };
    "npmlog-4.1.2" = {
      name = "npmlog";
      packageName = "npmlog";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-4.1.2.tgz";
        sha1 = "08a7f2a8bf734604779a9efa4ad5cc717abb954b";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "readable-stream-2.3.3" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.3.tgz";
        sha1 = "368f2512d79f9d46fdfc71349ae7878bbc1eb95c";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-1.0.3" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.3.tgz";
        sha1 = "0fc67d7c141825de94282dd536bec6b9bce860ab";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "hosted-git-info-2.5.0" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.5.0.tgz";
        sha1 = "6d60e34b3abbc8313062c3b798ef8d901a07af3c";
      };
    };
    "is-builtin-module-1.0.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-1.0.0.tgz";
        sha1 = "540572d34f7ac3119f8f76c30cbc1b1e037affbe";
      };
    };
    "validate-npm-package-license-3.0.1" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.1.tgz";
        sha1 = "2804babe712ad3379459acfbe24746ab2c303fbc";
      };
    };
    "builtin-modules-1.1.1" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-1.1.1.tgz";
        sha1 = "270f076c5a72c02f5b65a47df94c5fe3a278892f";
      };
    };
    "spdx-correct-1.0.2" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-1.0.2.tgz";
        sha1 = "4b3073d933ff51f3912f03ac5519498a4150db40";
      };
    };
    "spdx-expression-parse-1.0.4" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-1.0.4.tgz";
        sha1 = "9bdf2f20e1f40ed447fbe273266191fced51626c";
      };
    };
    "spdx-license-ids-1.2.2" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-1.2.2.tgz";
        sha1 = "c9df7a3424594ade6bd11900d596696dc06bac57";
      };
    };
    "osenv-0.1.4" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.4.tgz";
        sha1 = "42fe6d5953df06c8064be6f176c3d05aaaa34644";
      };
    };
    "validate-npm-package-name-3.0.0" = {
      name = "validate-npm-package-name";
      packageName = "validate-npm-package-name";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-name/-/validate-npm-package-name-3.0.0.tgz";
        sha1 = "5fa912d81eb7d0c74afc140de7317f0ca7df437e";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "builtins-1.0.3" = {
      name = "builtins";
      packageName = "builtins";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtins/-/builtins-1.0.3.tgz";
        sha1 = "cb94faeb61c8696451db36534e1422f94f0aee88";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "are-we-there-yet-1.1.4" = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.4.tgz";
        sha1 = "bb5dca382bb94f05e15194373d16fd3ba1ca110d";
      };
    };
    "console-control-strings-1.1.0" = {
      name = "console-control-strings";
      packageName = "console-control-strings";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz";
        sha1 = "3d7cf4464db6446ea644bf4b39507f9851008e8e";
      };
    };
    "gauge-2.7.4" = {
      name = "gauge";
      packageName = "gauge";
      version = "2.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/gauge/-/gauge-2.7.4.tgz";
        sha1 = "2c03405c7538c39d7eb37b317022e325fb018bf7";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "delegates-1.0.0" = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "84c6e159b81904fdca59a0ef44cd870d31250f9a";
      };
    };
    "aproba-1.2.0" = {
      name = "aproba";
      packageName = "aproba";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aproba/-/aproba-1.2.0.tgz";
        sha1 = "6802e6264efd18c790a1b0d517f0f2627bf2c94a";
      };
    };
    "has-unicode-2.0.1" = {
      name = "has-unicode";
      packageName = "has-unicode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
        sha1 = "e0e6fe6a28cf51138855e086d1691e771de2a8b9";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "wide-align-1.1.2" = {
      name = "wide-align";
      packageName = "wide-align";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.2.tgz";
        sha1 = "571e0f1b0604636ebc0dfc21b0339bbe31341710";
      };
    };
    "code-point-at-1.1.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "0d070b4d043a5bea33a2f1a40e2edb3d9a4ccf77";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "config-chain-1.1.11" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.11.tgz";
        sha1 = "aba09747dfbe4c3e70e766a6e41586e1859fc6f2";
      };
    };
    "ini-1.3.4" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.4.tgz";
        sha1 = "0537cb79daf59b59a1a517dff706c86ec039162e";
      };
    };
    "once-1.3.3" = {
      name = "once";
      packageName = "once";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.3.3.tgz";
        sha1 = "b2e261557ce4c314ec8304f3fa82663e4297ca20";
      };
    };
    "semver-4.3.6" = {
      name = "semver";
      packageName = "semver";
      version = "4.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-4.3.6.tgz";
        sha1 = "300bc6e0e86374f7ba61068b5b1ecd57fc6532da";
      };
    };
    "uid-number-0.0.5" = {
      name = "uid-number";
      packageName = "uid-number";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid-number/-/uid-number-0.0.5.tgz";
        sha1 = "5a3db23ef5dbd55b81fce0ec9a2ac6fccdebb81e";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha1 = "212d5bfe1318306a420f6402b8e26ff39647a849";
      };
    };
    "minipass-2.2.1" = {
      name = "minipass";
      packageName = "minipass";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-2.2.1.tgz";
        sha1 = "5ada97538b1027b4cf7213432428578cb564011f";
      };
    };
    "minizlib-1.0.3" = {
      name = "minizlib";
      packageName = "minizlib";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minizlib/-/minizlib-1.0.3.tgz";
        sha1 = "d5c1abf77be154619952e253336eccab9b2a32f5";
      };
    };
    "yallist-3.0.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-3.0.2.tgz";
        sha1 = "8452b4bb7e83c7c188d8041c1a837c773d6d8bb9";
      };
    };
    "fs-extra-0.6.4" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "0.6.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-0.6.4.tgz";
        sha1 = "f46f0c75b7841f8d200b3348cd4d691d5a099d15";
      };
    };
    "mkdirp-0.3.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz";
        sha1 = "de3e5f8961c88c787ee1368df849ac4413eca8d7";
      };
    };
    "walk-2.3.9" = {
      name = "walk";
      packageName = "walk";
      version = "2.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/walk/-/walk-2.3.9.tgz";
        sha1 = "31b4db6678f2ae01c39ea9fb8725a9031e558a7b";
      };
    };
    "ncp-0.4.2" = {
      name = "ncp";
      packageName = "ncp";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ncp/-/ncp-0.4.2.tgz";
        sha1 = "abcc6cbd3ec2ed2a729ff6e7c1fa8f01784a8574";
      };
    };
    "jsonfile-1.0.1" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-1.0.1.tgz";
        sha1 = "ea5efe40b83690b98667614a7392fc60e842c0dd";
      };
    };
    "foreachasync-3.0.0" = {
      name = "foreachasync";
      packageName = "foreachasync";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreachasync/-/foreachasync-3.0.0.tgz";
        sha1 = "5502987dc8714be3392097f32e0071c9dee07cf6";
      };
    };
    "cli-1.0.1" = {
      name = "cli";
      packageName = "cli";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli/-/cli-1.0.1.tgz";
        sha1 = "22817534f24bfa4950c34d532d48ecbc621b8c14";
      };
    };
    "console-browserify-1.1.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz";
        sha1 = "f0241c45730a9fc6323b206dbf38edc741d0bb10";
      };
    };
    "htmlparser2-3.8.3" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.3.tgz";
        sha1 = "996c28b191516a8be86501a7d79757e5c70c1068";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha1 = "5166e286457f03306064be5497e8dbb0c3d32083";
      };
    };
    "shelljs-0.3.0" = {
      name = "shelljs";
      packageName = "shelljs";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shelljs/-/shelljs-0.3.0.tgz";
        sha1 = "3596e6307a781544f591f37da618360f31db57b1";
      };
    };
    "strip-json-comments-1.0.4" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz";
        sha1 = "1e15fbcac97d3ee99bf2d73b4c656b082bbafb91";
      };
    };
    "lodash-3.7.0" = {
      name = "lodash";
      packageName = "lodash";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-3.7.0.tgz";
        sha1 = "3678bd8ab995057c07ade836ed2ef087da811d45";
      };
    };
    "glob-7.1.2" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.2.tgz";
        sha1 = "c19c9df9a028702d678612384a6552404c636d15";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "brace-expansion-1.1.8" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz";
        sha1 = "c07b211c7c952ec1f8efd51a77ef0d1d3990a292";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "date-now-0.1.4" = {
      name = "date-now";
      packageName = "date-now";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-now/-/date-now-0.1.4.tgz";
        sha1 = "eaf439fd4d4848ad74e5cc7dbef200672b9e345b";
      };
    };
    "domhandler-2.3.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.3.0.tgz";
        sha1 = "2de59a0822d5027fabff6f032c2b25a2a8abe738";
      };
    };
    "domutils-1.5.1" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.5.1.tgz";
        sha1 = "dcd8488a26f563d61079e48c9f7b7e32373682cf";
      };
    };
    "domelementtype-1.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.0.tgz";
        sha1 = "b17aed82e8ab59e52dd9c19b1756e0fc187204c2";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "entities-1.0.0" = {
      name = "entities";
      packageName = "entities";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.0.0.tgz";
        sha1 = "b2987aa3821347fcde642b24fdfc9e4fb712bf26";
      };
    };
    "dom-serializer-0.1.0" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.1.0.tgz";
        sha1 = "073c697546ce0780ce23be4a28e293e40bc30c82";
      };
    };
    "domelementtype-1.1.3" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.1.3.tgz";
        sha1 = "bd28773e2642881aec51544924299c5cd822185b";
      };
    };
    "entities-1.1.1" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.1.tgz";
        sha1 = "6e5c2d0a5621b5dadaecef80b90edfb5cd7772f0";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "good-listener-1.2.2" = {
      name = "good-listener";
      packageName = "good-listener";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/good-listener/-/good-listener-1.2.2.tgz";
        sha1 = "d53b30cdf9313dffb7dc9a0d477096aa6d145c50";
      };
    };
    "select-1.1.2" = {
      name = "select";
      packageName = "select";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/select/-/select-1.1.2.tgz";
        sha1 = "0e7350acdec80b1108528786ec1d4418d11b396d";
      };
    };
    "tiny-emitter-2.0.2" = {
      name = "tiny-emitter";
      packageName = "tiny-emitter";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-emitter/-/tiny-emitter-2.0.2.tgz";
        sha1 = "82d27468aca5ade8e5fd1e6d22b57dd43ebdfb7c";
      };
    };
    "delegate-3.1.3" = {
      name = "delegate";
      packageName = "delegate";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegate/-/delegate-3.1.3.tgz";
        sha1 = "9a8251a777d7025faa55737bc3b071742127a9fd";
      };
    };
  };
  args = {
    name = "rhodecode-enterprise";
    packageName = "rhodecode-enterprise";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."grunt-0.4.5"
      sources."grunt-contrib-copy-1.0.0"
      (sources."grunt-contrib-concat-0.5.1" // {
        dependencies = [
          sources."chalk-0.5.1"
          sources."ansi-styles-1.1.0"
          sources."has-ansi-0.1.0"
          sources."strip-ansi-0.3.0"
          sources."supports-color-0.2.0"
          sources."ansi-regex-0.2.1"
        ];
      })
      sources."grunt-contrib-jshint-0.12.0"
      (sources."grunt-contrib-less-1.4.1" // {
        dependencies = [
          sources."async-2.5.0"
          sources."lodash-4.17.4"
        ];
      })
      (sources."grunt-contrib-watch-0.6.1" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."async-0.2.10"
        ];
      })
      sources."crisper-2.1.1"
      (sources."vulcanize-1.16.0" // {
        dependencies = [
          sources."nopt-3.0.6"
        ];
      })
      sources."grunt-crisper-1.0.1"
      (sources."grunt-vulcanize-1.0.0" // {
        dependencies = [
          sources."crisper-1.2.0"
          sources."nopt-3.0.6"
        ];
      })
      sources."node2nix-1.3.0"
      (sources."jshint-2.9.5" // {
        dependencies = [
          sources."minimatch-3.0.4"
          sources."lodash-3.7.0"
        ];
      })
      sources."bower-1.8.2"
      sources."jquery-1.11.3"
      sources."favico.js-0.3.10"
      sources."clipboard-1.7.1"
      sources."moment-2.18.1"
      sources."mousetrap-1.6.1"
      sources."appenlight-client-git+https://git@github.com/AppEnlight/appenlight-client-js.git#0.5.1"
      sources."async-0.1.22"
      sources."coffee-script-1.3.3"
      sources."colors-0.6.2"
      sources."dateformat-1.0.2-1.2.3"
      sources."eventemitter2-0.4.14"
      (sources."findup-sync-0.1.3" // {
        dependencies = [
          sources."glob-3.2.11"
          sources."lodash-2.4.2"
          sources."minimatch-0.3.0"
        ];
      })
      (sources."glob-3.1.21" // {
        dependencies = [
          sources."inherits-1.0.2"
        ];
      })
      sources."hooker-0.2.3"
      sources."iconv-lite-0.2.11"
      sources."minimatch-0.2.14"
      sources."nopt-1.0.10"
      sources."rimraf-2.2.8"
      sources."lodash-0.9.2"
      sources."underscore.string-2.2.1"
      sources."which-1.0.9"
      sources."js-yaml-2.0.5"
      sources."exit-0.1.2"
      sources."getobject-0.1.0"
      sources."grunt-legacy-util-0.2.0"
      (sources."grunt-legacy-log-0.1.3" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."underscore.string-2.3.3"
        ];
      })
      sources."inherits-2.0.3"
      sources."lru-cache-2.7.3"
      sources."sigmund-1.0.1"
      sources."graceful-fs-1.2.3"
      sources."abbrev-1.1.0"
      (sources."argparse-0.1.16" // {
        dependencies = [
          sources."underscore.string-2.4.0"
        ];
      })
      sources."esprima-1.0.4"
      sources."underscore-1.7.0"
      (sources."grunt-legacy-log-utils-0.1.1" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."underscore.string-2.3.3"
        ];
      })
      sources."chalk-1.1.3"
      sources."file-sync-cmp-0.1.1"
      sources."ansi-styles-2.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."ansi-regex-2.1.1"
      sources."source-map-0.3.0"
      sources."amdefine-1.0.1"
      (sources."less-2.7.2" // {
        dependencies = [
          sources."graceful-fs-4.1.11"
          sources."source-map-0.5.7"
        ];
      })
      sources."errno-0.1.4"
      sources."image-size-0.5.5"
      sources."mime-1.4.0"
      sources."mkdirp-0.5.1"
      sources."promise-7.3.1"
      sources."request-2.82.0"
      sources."prr-0.0.0"
      sources."minimist-0.0.8"
      sources."asap-2.0.6"
      sources."aws-sign2-0.7.0"
      sources."aws4-1.6.0"
      sources."caseless-0.12.0"
      sources."combined-stream-1.0.5"
      sources."extend-3.0.1"
      sources."forever-agent-0.6.1"
      sources."form-data-2.3.1"
      sources."har-validator-5.0.3"
      sources."hawk-6.0.2"
      sources."http-signature-1.2.0"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."json-stringify-safe-5.0.1"
      sources."mime-types-2.1.17"
      sources."oauth-sign-0.8.2"
      sources."performance-now-2.1.0"
      sources."qs-6.5.1"
      sources."safe-buffer-5.1.1"
      sources."stringstream-0.0.5"
      sources."tough-cookie-2.3.3"
      sources."tunnel-agent-0.6.0"
      sources."uuid-3.1.0"
      sources."delayed-stream-1.0.0"
      sources."asynckit-0.4.0"
      sources."ajv-5.2.2"
      sources."har-schema-2.0.0"
      sources."co-4.6.0"
      sources."fast-deep-equal-1.0.0"
      sources."json-schema-traverse-0.3.1"
      sources."json-stable-stringify-1.0.1"
      sources."jsonify-0.0.0"
      sources."hoek-4.2.0"
      sources."boom-4.3.1"
      (sources."cryptiles-3.1.2" // {
        dependencies = [
          sources."boom-5.2.0"
        ];
      })
      sources."sntp-2.0.2"
      sources."assert-plus-1.0.0"
      sources."jsprim-1.4.1"
      sources."sshpk-1.13.1"
      sources."extsprintf-1.3.0"
      sources."json-schema-0.2.3"
      sources."verror-1.10.0"
      sources."core-util-is-1.0.2"
      sources."asn1-0.2.3"
      sources."dashdash-1.14.1"
      sources."getpass-0.1.7"
      sources."jsbn-0.1.1"
      sources."tweetnacl-0.14.5"
      sources."ecc-jsbn-0.1.1"
      sources."bcrypt-pbkdf-1.0.1"
      sources."mime-db-1.30.0"
      sources."punycode-1.4.1"
      sources."gaze-0.5.2"
      (sources."tiny-lr-fork-0.0.5" // {
        dependencies = [
          sources."qs-0.5.6"
        ];
      })
      (sources."globule-0.1.0" // {
        dependencies = [
          sources."lodash-1.0.2"
        ];
      })
      sources."faye-websocket-0.4.4"
      (sources."noptify-0.0.3" // {
        dependencies = [
          sources."nopt-2.0.0"
        ];
      })
      sources."debug-0.7.4"
      sources."command-line-args-3.0.5"
      sources."command-line-usage-3.0.8"
      sources."dom5-1.3.6"
      sources."array-back-1.0.4"
      sources."feature-detect-es6-1.3.1"
      sources."find-replace-1.0.3"
      sources."typical-2.6.1"
      sources."test-value-2.1.0"
      sources."ansi-escape-sequences-3.0.0"
      sources."table-layout-0.3.0"
      sources."core-js-2.5.1"
      sources."deep-extend-0.4.2"
      sources."wordwrapjs-2.0.0"
      sources."reduce-flatten-1.0.1"
      sources."@types/clone-0.1.30"
      sources."@types/node-4.2.20"
      (sources."@types/parse5-0.0.31" // {
        dependencies = [
          sources."@types/node-6.0.88"
        ];
      })
      sources."clone-1.0.2"
      sources."parse5-1.5.1"
      sources."es6-promise-2.3.0"
      (sources."hydrolysis-1.25.0" // {
        dependencies = [
          sources."dom5-1.1.0"
        ];
      })
      sources."path-posix-1.0.0"
      sources."acorn-3.3.0"
      sources."babel-polyfill-6.26.0"
      sources."doctrine-0.7.2"
      (sources."escodegen-1.9.0" // {
        dependencies = [
          sources."estraverse-4.2.0"
          sources."esutils-2.0.2"
          sources."esprima-3.1.3"
          sources."source-map-0.5.7"
        ];
      })
      (sources."espree-3.5.1" // {
        dependencies = [
          sources."acorn-5.1.2"
        ];
      })
      sources."estraverse-3.1.0"
      sources."path-is-absolute-1.0.1"
      (sources."babel-runtime-6.26.0" // {
        dependencies = [
          sources."regenerator-runtime-0.11.0"
        ];
      })
      sources."regenerator-runtime-0.10.5"
      sources."esutils-1.1.6"
      sources."isarray-0.0.1"
      sources."optionator-0.8.2"
      sources."prelude-ls-1.1.2"
      sources."deep-is-0.1.3"
      sources."wordwrap-1.0.0"
      sources."type-check-0.3.2"
      sources."levn-0.3.0"
      sources."fast-levenshtein-2.0.6"
      sources."acorn-jsx-3.0.1"
      sources."object-assign-4.1.1"
      sources."optparse-1.0.5"
      sources."semver-5.4.1"
      (sources."npm-registry-client-8.4.0" // {
        dependencies = [
          sources."graceful-fs-4.1.11"
        ];
      })
      (sources."npmconf-2.1.2" // {
        dependencies = [
          sources."nopt-3.0.6"
          sources."once-1.3.3"
          sources."semver-4.3.6"
        ];
      })
      sources."tar-3.1.15"
      sources."temp-0.8.3"
      (sources."fs.extra-1.3.2" // {
        dependencies = [
          sources."mkdirp-0.3.5"
        ];
      })
      sources."findit-2.0.0"
      sources."base64-js-1.2.1"
      sources."slasp-0.0.4"
      sources."nijs-0.0.23"
      sources."concat-stream-1.6.0"
      sources."normalize-package-data-2.4.0"
      sources."npm-package-arg-5.1.2"
      sources."once-1.4.0"
      sources."retry-0.10.1"
      sources."slide-1.1.6"
      sources."ssri-4.1.6"
      sources."npmlog-4.1.2"
      sources."typedarray-0.0.6"
      (sources."readable-stream-2.3.3" // {
        dependencies = [
          sources."isarray-1.0.0"
        ];
      })
      sources."process-nextick-args-1.0.7"
      sources."string_decoder-1.0.3"
      sources."util-deprecate-1.0.2"
      sources."hosted-git-info-2.5.0"
      sources."is-builtin-module-1.0.0"
      sources."validate-npm-package-license-3.0.1"
      sources."builtin-modules-1.1.1"
      sources."spdx-correct-1.0.2"
      sources."spdx-expression-parse-1.0.4"
      sources."spdx-license-ids-1.2.2"
      sources."osenv-0.1.4"
      sources."validate-npm-package-name-3.0.0"
      sources."os-homedir-1.0.2"
      sources."os-tmpdir-1.0.2"
      sources."builtins-1.0.3"
      sources."wrappy-1.0.2"
      sources."are-we-there-yet-1.1.4"
      sources."console-control-strings-1.1.0"
      sources."gauge-2.7.4"
      sources."set-blocking-2.0.0"
      sources."delegates-1.0.0"
      sources."aproba-1.2.0"
      sources."has-unicode-2.0.1"
      sources."signal-exit-3.0.2"
      sources."string-width-1.0.2"
      sources."wide-align-1.1.2"
      sources."code-point-at-1.1.0"
      sources."is-fullwidth-code-point-1.0.0"
      sources."number-is-nan-1.0.1"
      sources."config-chain-1.1.11"
      sources."ini-1.3.4"
      sources."uid-number-0.0.5"
      sources."proto-list-1.2.4"
      sources."minipass-2.2.1"
      sources."minizlib-1.0.3"
      sources."yallist-3.0.2"
      (sources."fs-extra-0.6.4" // {
        dependencies = [
          sources."mkdirp-0.3.5"
        ];
      })
      sources."walk-2.3.9"
      sources."ncp-0.4.2"
      sources."jsonfile-1.0.1"
      sources."foreachasync-3.0.0"
      (sources."cli-1.0.1" // {
        dependencies = [
          sources."glob-7.1.2"
          sources."minimatch-3.0.4"
        ];
      })
      sources."console-browserify-1.1.0"
      (sources."htmlparser2-3.8.3" // {
        dependencies = [
          sources."readable-stream-1.1.14"
          sources."string_decoder-0.10.31"
        ];
      })
      sources."shelljs-0.3.0"
      sources."strip-json-comments-1.0.4"
      sources."fs.realpath-1.0.0"
      sources."inflight-1.0.6"
      sources."brace-expansion-1.1.8"
      sources."balanced-match-1.0.0"
      sources."concat-map-0.0.1"
      sources."date-now-0.1.4"
      sources."domhandler-2.3.0"
      sources."domutils-1.5.1"
      sources."domelementtype-1.3.0"
      sources."entities-1.0.0"
      (sources."dom-serializer-0.1.0" // {
        dependencies = [
          sources."domelementtype-1.1.3"
          sources."entities-1.1.1"
        ];
      })
      sources."good-listener-1.2.2"
      sources."select-1.1.2"
      sources."tiny-emitter-2.0.2"
      sources."delegate-3.1.3"
    ];
    meta = {
    };
    production = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}