# This file has been generated by node2nix 1.0.0. Do not edit!

{nodeEnv, fetchurl, fetchgit}:

let
  sources = {
    "grunt-0.4.5" = {
      name = "grunt";
      packageName = "grunt";
      version = "0.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz";
        sha1 = "56937cd5194324adff6d207631832a9d6ba4e7f0";
      };
    };
    "grunt-contrib-copy-1.0.0" = {
      name = "grunt-contrib-copy";
      packageName = "grunt-contrib-copy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-copy/-/grunt-contrib-copy-1.0.0.tgz";
        sha1 = "7060c6581e904b8ab0d00f076e0a8f6e3e7c3573";
      };
    };
    "grunt-contrib-concat-0.5.1" = {
      name = "grunt-contrib-concat";
      packageName = "grunt-contrib-concat";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-concat/-/grunt-contrib-concat-0.5.1.tgz";
        sha1 = "953c6efdfdfd2c107ab9c85077f2d4b24d31cd49";
      };
    };
    "grunt-contrib-jshint-0.12.0" = {
      name = "grunt-contrib-jshint";
      packageName = "grunt-contrib-jshint";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-jshint/-/grunt-contrib-jshint-0.12.0.tgz";
        sha1 = "f6b2f06fc715264837a7ab6c69a1ce1a689c2c29";
      };
    };
    "grunt-contrib-less-1.4.0" = {
      name = "grunt-contrib-less";
      packageName = "grunt-contrib-less";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-less/-/grunt-contrib-less-1.4.0.tgz";
        sha1 = "17ee79cad21c9720ee07b3a991fab5103b513514";
      };
    };
    "grunt-contrib-watch-0.6.1" = {
      name = "grunt-contrib-watch";
      packageName = "grunt-contrib-watch";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-contrib-watch/-/grunt-contrib-watch-0.6.1.tgz";
        sha1 = "64fdcba25a635f5b4da1b6ce6f90da0aeb6e3f15";
      };
    };
    "crisper-2.0.2" = {
      name = "crisper";
      packageName = "crisper";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/crisper/-/crisper-2.0.2.tgz";
        sha1 = "188a7da3d00dcf0c64eff7f253d23dacffba7197";
      };
    };
    "vulcanize-1.14.8" = {
      name = "vulcanize";
      packageName = "vulcanize";
      version = "1.14.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/vulcanize/-/vulcanize-1.14.8.tgz";
        sha1 = "3cdd6f81d9baf2c5796ddd6d2d289e45975086f7";
      };
    };
    "grunt-crisper-1.0.1" = {
      name = "grunt-crisper";
      packageName = "grunt-crisper";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-crisper/-/grunt-crisper-1.0.1.tgz";
        sha1 = "e7c091dcaff10deb0091e3035ca7e54008991fe7";
      };
    };
    "grunt-vulcanize-1.0.0" = {
      name = "grunt-vulcanize";
      packageName = "grunt-vulcanize";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-vulcanize/-/grunt-vulcanize-1.0.0.tgz";
        sha1 = "f4d6cfef274f8216c06f6c290e7dbb3b9e9e3b0f";
      };
    };
    "jshint-2.9.3" = {
      name = "jshint";
      packageName = "jshint";
      version = "2.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/jshint/-/jshint-2.9.3.tgz";
        sha1 = "a2e14ff85c2d6bf8c8080e5aa55129ebc6a2d320";
      };
    };
    "async-0.1.22" = {
      name = "async";
      packageName = "async";
      version = "0.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.1.22.tgz";
        sha1 = "0fc1aaa088a0e3ef0ebe2d8831bab0dcf8845061";
      };
    };
    "coffee-script-1.3.3" = {
      name = "coffee-script";
      packageName = "coffee-script";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/coffee-script/-/coffee-script-1.3.3.tgz";
        sha1 = "150d6b4cb522894369efed6a2101c20bc7f4a4f4";
      };
    };
    "colors-0.6.2" = {
      name = "colors";
      packageName = "colors";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-0.6.2.tgz";
        sha1 = "2423fe6678ac0c5dae8852e5d0e5be08c997abcc";
      };
    };
    "dateformat-1.0.2-1.2.3" = {
      name = "dateformat";
      packageName = "dateformat";
      version = "1.0.2-1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dateformat/-/dateformat-1.0.2-1.2.3.tgz";
        sha1 = "b0220c02de98617433b72851cf47de3df2cdbee9";
      };
    };
    "eventemitter2-0.4.14" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "0.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-0.4.14.tgz";
        sha1 = "8f61b75cde012b2e9eb284d4545583b5643b61ab";
      };
    };
    "findup-sync-0.1.3" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-0.1.3.tgz";
        sha1 = "7f3e7a97b82392c653bf06589bd85190e93c3683";
      };
    };
    "glob-3.1.21" = {
      name = "glob";
      packageName = "glob";
      version = "3.1.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-3.1.21.tgz";
        sha1 = "d29e0a055dea5138f4d07ed40e8982e83c2066cd";
      };
    };
    "hooker-0.2.3" = {
      name = "hooker";
      packageName = "hooker";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hooker/-/hooker-0.2.3.tgz";
        sha1 = "b834f723cc4a242aa65963459df6d984c5d3d959";
      };
    };
    "iconv-lite-0.2.11" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.2.11.tgz";
        sha1 = "1ce60a3a57864a292d1321ff4609ca4bb965adc8";
      };
    };
    "minimatch-0.2.14" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "0.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-0.2.14.tgz";
        sha1 = "c74e780574f63c6f9a090e90efbe6ef53a6a756a";
      };
    };
    "nopt-1.0.10" = {
      name = "nopt";
      packageName = "nopt";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-1.0.10.tgz";
        sha1 = "6ddd21bd2a31417b92727dd585f8a6f37608ebee";
      };
    };
    "rimraf-2.2.8" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.2.8.tgz";
        sha1 = "e439be2aaee327321952730f99a8929e4fc50582";
      };
    };
    "lodash-0.9.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-0.9.2.tgz";
        sha1 = "8f3499c5245d346d682e5b0d3b40767e09f1a92c";
      };
    };
    "underscore.string-2.2.1" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.2.1.tgz";
        sha1 = "d7c0fa2af5d5a1a67f4253daee98132e733f0f19";
      };
    };
    "which-1.0.9" = {
      name = "which";
      packageName = "which";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.0.9.tgz";
        sha1 = "460c1da0f810103d0321a9b633af9e575e64486f";
      };
    };
    "js-yaml-2.0.5" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-2.0.5.tgz";
        sha1 = "a25ae6509999e97df278c6719da11bd0687743a8";
      };
    };
    "exit-0.1.2" = {
      name = "exit";
      packageName = "exit";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/exit/-/exit-0.1.2.tgz";
        sha1 = "0632638f8d877cc82107d30a0fff1a17cba1cd0c";
      };
    };
    "getobject-0.1.0" = {
      name = "getobject";
      packageName = "getobject";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/getobject/-/getobject-0.1.0.tgz";
        sha1 = "047a449789fa160d018f5486ed91320b6ec7885c";
      };
    };
    "grunt-legacy-util-0.2.0" = {
      name = "grunt-legacy-util";
      packageName = "grunt-legacy-util";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-util/-/grunt-legacy-util-0.2.0.tgz";
        sha1 = "93324884dbf7e37a9ff7c026dff451d94a9e554b";
      };
    };
    "grunt-legacy-log-0.1.3" = {
      name = "grunt-legacy-log";
      packageName = "grunt-legacy-log";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log/-/grunt-legacy-log-0.1.3.tgz";
        sha1 = "ec29426e803021af59029f87d2f9cd7335a05531";
      };
    };
    "glob-3.2.11" = {
      name = "glob";
      packageName = "glob";
      version = "3.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-3.2.11.tgz";
        sha1 = "4a973f635b9190f715d10987d5c00fd2815ebe3d";
      };
    };
    "lodash-2.4.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-2.4.2.tgz";
        sha1 = "fadd834b9683073da179b3eae6d9c0d15053f73e";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "minimatch-0.3.0" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz";
        sha1 = "275d8edaac4f1bb3326472089e7949c8394699dd";
      };
    };
    "lru-cache-2.7.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz";
        sha1 = "6d4524e8b955f95d4f5b58851ce21dd72fb4e952";
      };
    };
    "sigmund-1.0.1" = {
      name = "sigmund";
      packageName = "sigmund";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz";
        sha1 = "3ff21f198cad2175f9f3b781853fd94d0d19b590";
      };
    };
    "graceful-fs-1.2.3" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-1.2.3.tgz";
        sha1 = "15a4806a57547cb2d2dbf27f42e89a8c3451b364";
      };
    };
    "inherits-1.0.2" = {
      name = "inherits";
      packageName = "inherits";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-1.0.2.tgz";
        sha1 = "ca4309dadee6b54cc0b8d247e8d7c7a0975bdc9b";
      };
    };
    "abbrev-1.0.9" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.0.9.tgz";
        sha1 = "91b4792588a7738c25f35dd6f63752a2f8776135";
      };
    };
    "argparse-0.1.16" = {
      name = "argparse";
      packageName = "argparse";
      version = "0.1.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-0.1.16.tgz";
        sha1 = "cfd01e0fbba3d6caed049fbd758d40f65196f57c";
      };
    };
    "esprima-1.0.4" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.0.4.tgz";
        sha1 = "9f557e08fc3b4d26ece9dd34f8fbf476b62585ad";
      };
    };
    "underscore-1.7.0" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz";
        sha1 = "6bbaf0877500d36be34ecaa584e0db9fef035209";
      };
    };
    "underscore.string-2.4.0" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.4.0.tgz";
        sha1 = "8cdd8fbac4e2d2ea1e7e2e8097c42f442280f85b";
      };
    };
    "grunt-legacy-log-utils-0.1.1" = {
      name = "grunt-legacy-log-utils";
      packageName = "grunt-legacy-log-utils";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-legacy-log-utils/-/grunt-legacy-log-utils-0.1.1.tgz";
        sha1 = "c0706b9dd9064e116f36f23fe4e6b048672c0f7e";
      };
    };
    "underscore.string-2.3.3" = {
      name = "underscore.string";
      packageName = "underscore.string";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore.string/-/underscore.string-2.3.3.tgz";
        sha1 = "71c08bf6b428b1133f37e78fa3a21c82f7329b0d";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "file-sync-cmp-0.1.1" = {
      name = "file-sync-cmp";
      packageName = "file-sync-cmp";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-sync-cmp/-/file-sync-cmp-0.1.1.tgz";
        sha1 = "a5e7a8ffbfa493b43b923bbd4ca89a53b63b612b";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz";
        sha1 = "c5061b6e0ef8a81775e50f5d66151bf6bf371107";
      };
    };
    "chalk-0.5.1" = {
      name = "chalk";
      packageName = "chalk";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-0.5.1.tgz";
        sha1 = "663b3a648b68b55d04690d49167aa837858f2174";
      };
    };
    "source-map-0.3.0" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.3.0.tgz";
        sha1 = "8586fb9a5a005e5b501e21cd18b6f21b457ad1f9";
      };
    };
    "ansi-styles-1.1.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-1.1.0.tgz";
        sha1 = "eaecbf66cd706882760b2f4691582b8f55d7a7de";
      };
    };
    "has-ansi-0.1.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-0.1.0.tgz";
        sha1 = "84f265aae8c0e6a88a12d7022894b7568894c62e";
      };
    };
    "strip-ansi-0.3.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-0.3.0.tgz";
        sha1 = "25f48ea22ca79187f3174a4db8759347bb126220";
      };
    };
    "supports-color-0.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-0.2.0.tgz";
        sha1 = "d92de2694eb3f67323973d7ae3d8b55b4c22190a";
      };
    };
    "ansi-regex-0.2.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-0.2.1.tgz";
        sha1 = "0d8e946967a3d8143f93e24e298525fc1b2235f9";
      };
    };
    "amdefine-1.0.0" = {
      name = "amdefine";
      packageName = "amdefine";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/amdefine/-/amdefine-1.0.0.tgz";
        sha1 = "fd17474700cb5cc9c2b709f0be9d23ce3c198c33";
      };
    };
    "async-2.0.1" = {
      name = "async";
      packageName = "async";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.0.1.tgz";
        sha1 = "b709cc0280a9c36f09f4536be823c838a9049e25";
      };
    };
    "less-2.7.1" = {
      name = "less";
      packageName = "less";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/less/-/less-2.7.1.tgz";
        sha1 = "6cbfea22b3b830304e9a5fb371d54fa480c9d7cf";
      };
    };
    "lodash-4.15.0" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.15.0.tgz";
        sha1 = "3162391d8f0140aa22cf8f6b3c34d6b7f63d3aa9";
      };
    };
    "errno-0.1.4" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.4.tgz";
        sha1 = "b896e23a9e5e8ba33871fc996abd3635fc9a1c7d";
      };
    };
    "graceful-fs-4.1.6" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.6.tgz";
        sha1 = "514c38772b31bee2e08bedc21a0aeb3abf54c19e";
      };
    };
    "image-size-0.5.0" = {
      name = "image-size";
      packageName = "image-size";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-size/-/image-size-0.5.0.tgz";
        sha1 = "be7aed1c37b5ac3d9ba1d66a24b4c47ff8397651";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "promise-7.1.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.1.1.tgz";
        sha1 = "489654c692616b8aa55b0724fa809bb7db49c5bf";
      };
    };
    "source-map-0.5.6" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.6.tgz";
        sha1 = "75ce38f52bf0733c5a7f0c118d81334a2bb5f412";
      };
    };
    "prr-0.0.0" = {
      name = "prr";
      packageName = "prr";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-0.0.0.tgz";
        sha1 = "1a84b85908325501411853d0081ee3fa86e2926a";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "asap-2.0.4" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.4.tgz";
        sha1 = "b391bf7f6bfbc65706022fec8f49c4b07fecf589";
      };
    };
    "gaze-0.5.2" = {
      name = "gaze";
      packageName = "gaze";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gaze/-/gaze-0.5.2.tgz";
        sha1 = "40b709537d24d1d45767db5a908689dfe69ac44f";
      };
    };
    "tiny-lr-fork-0.0.5" = {
      name = "tiny-lr-fork";
      packageName = "tiny-lr-fork";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tiny-lr-fork/-/tiny-lr-fork-0.0.5.tgz";
        sha1 = "1e99e1e2a8469b736ab97d97eefa98c71f76ed0a";
      };
    };
    "async-0.2.10" = {
      name = "async";
      packageName = "async";
      version = "0.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.2.10.tgz";
        sha1 = "b6bbe0b0674b9d719708ca38de8c237cb526c3d1";
      };
    };
    "globule-0.1.0" = {
      name = "globule";
      packageName = "globule";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globule/-/globule-0.1.0.tgz";
        sha1 = "d9c8edde1da79d125a151b79533b978676346ae5";
      };
    };
    "lodash-1.0.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-1.0.2.tgz";
        sha1 = "8f57560c83b59fc270bd3d561b690043430e2551";
      };
    };
    "qs-0.5.6" = {
      name = "qs";
      packageName = "qs";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-0.5.6.tgz";
        sha1 = "31b1ad058567651c526921506b9a8793911a0384";
      };
    };
    "faye-websocket-0.4.4" = {
      name = "faye-websocket";
      packageName = "faye-websocket";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.4.4.tgz";
        sha1 = "c14c5b3bf14d7417ffbfd990c0a7495cd9f337bc";
      };
    };
    "noptify-0.0.3" = {
      name = "noptify";
      packageName = "noptify";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/noptify/-/noptify-0.0.3.tgz";
        sha1 = "58f654a73d9753df0c51d9686dc92104a67f4bbb";
      };
    };
    "debug-0.7.4" = {
      name = "debug";
      packageName = "debug";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-0.7.4.tgz";
        sha1 = "06e1ea8082c2cb14e39806e22e2f6f757f92af39";
      };
    };
    "nopt-2.0.0" = {
      name = "nopt";
      packageName = "nopt";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-2.0.0.tgz";
        sha1 = "ca7416f20a5e3f9c3b86180f96295fa3d0b52e0d";
      };
    };
    "command-line-args-2.1.6" = {
      name = "command-line-args";
      packageName = "command-line-args";
      version = "2.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-args/-/command-line-args-2.1.6.tgz";
        sha1 = "f197d6eaff34c9085577484b2864375b294f5697";
      };
    };
    "dom5-1.3.3" = {
      name = "dom5";
      packageName = "dom5";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom5/-/dom5-1.3.3.tgz";
        sha1 = "07e514522c245c7aa8512aa3f9118e8bcab9f909";
      };
    };
    "array-back-1.0.3" = {
      name = "array-back";
      packageName = "array-back";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-back/-/array-back-1.0.3.tgz";
        sha1 = "f1128a5cf1b91c80bed4a218f8c5b635c8b10663";
      };
    };
    "command-line-usage-2.0.5" = {
      name = "command-line-usage";
      packageName = "command-line-usage";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-usage/-/command-line-usage-2.0.5.tgz";
        sha1 = "f80c35ca5e8624841923ea3be3b9bfbf4f7be27b";
      };
    };
    "core-js-2.4.1" = {
      name = "core-js";
      packageName = "core-js";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz";
        sha1 = "4de911e667b0eae9124e34254b53aea6fc618d3e";
      };
    };
    "feature-detect-es6-1.3.1" = {
      name = "feature-detect-es6";
      packageName = "feature-detect-es6";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/feature-detect-es6/-/feature-detect-es6-1.3.1.tgz";
        sha1 = "f888736af9cb0c91f55663bfa4762eb96ee7047f";
      };
    };
    "find-replace-1.0.2" = {
      name = "find-replace";
      packageName = "find-replace";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-replace/-/find-replace-1.0.2.tgz";
        sha1 = "a2d6ce740d15f0d92b1b26763e2ce9c0e361fd98";
      };
    };
    "typical-2.5.0" = {
      name = "typical";
      packageName = "typical";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typical/-/typical-2.5.0.tgz";
        sha1 = "81244918aa28180c9e602aa457173404be0604f1";
      };
    };
    "ansi-escape-sequences-2.2.2" = {
      name = "ansi-escape-sequences";
      packageName = "ansi-escape-sequences";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-escape-sequences/-/ansi-escape-sequences-2.2.2.tgz";
        sha1 = "174c78d6f8b7de75f8957ae81c7f72210c701635";
      };
    };
    "column-layout-2.1.4" = {
      name = "column-layout";
      packageName = "column-layout";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/column-layout/-/column-layout-2.1.4.tgz";
        sha1 = "ed2857092ccf8338026fe538379d9672d70b3641";
      };
    };
    "wordwrapjs-1.2.1" = {
      name = "wordwrapjs";
      packageName = "wordwrapjs";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrapjs/-/wordwrapjs-1.2.1.tgz";
        sha1 = "754a5ea0664cfbff50540dc32d67bda3289fc34b";
      };
    };
    "collect-all-0.2.1" = {
      name = "collect-all";
      packageName = "collect-all";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/collect-all/-/collect-all-0.2.1.tgz";
        sha1 = "7225fb4585c22d4ffac886f0abaf5abc563a1a6a";
      };
    };
    "stream-connect-1.0.2" = {
      name = "stream-connect";
      packageName = "stream-connect";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-connect/-/stream-connect-1.0.2.tgz";
        sha1 = "18bc81f2edb35b8b5d9a8009200a985314428a97";
      };
    };
    "stream-via-0.1.1" = {
      name = "stream-via";
      packageName = "stream-via";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-via/-/stream-via-0.1.1.tgz";
        sha1 = "0cee5df9c959fb1d3f4eda4819f289d5f9205afc";
      };
    };
    "collect-json-1.0.8" = {
      name = "collect-json";
      packageName = "collect-json";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/collect-json/-/collect-json-1.0.8.tgz";
        sha1 = "aa2fa52b4d1d9444ce690f07a1e3617ab74bb827";
      };
    };
    "deep-extend-0.4.1" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.4.1.tgz";
        sha1 = "efe4113d08085f4e6f9687759810f807469e2253";
      };
    };
    "object-tools-2.0.6" = {
      name = "object-tools";
      packageName = "object-tools";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-tools/-/object-tools-2.0.6.tgz";
        sha1 = "f3fe1c350cda4a6f5d99d9646dc4892a02476ddd";
      };
    };
    "collect-all-1.0.2" = {
      name = "collect-all";
      packageName = "collect-all";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/collect-all/-/collect-all-1.0.2.tgz";
        sha1 = "39450f1e7aa6086570a006bce93ccf1218a77ea1";
      };
    };
    "stream-via-1.0.3" = {
      name = "stream-via";
      packageName = "stream-via";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-via/-/stream-via-1.0.3.tgz";
        sha1 = "cebd32a5a59d74b3b68e3404942e867184ad4ac9";
      };
    };
    "object-get-2.1.0" = {
      name = "object-get";
      packageName = "object-get";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-get/-/object-get-2.1.0.tgz";
        sha1 = "722bbdb60039efa47cad3c6dc2ce51a85c02c5ae";
      };
    };
    "test-value-1.1.0" = {
      name = "test-value";
      packageName = "test-value";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/test-value/-/test-value-1.1.0.tgz";
        sha1 = "a09136f72ec043d27c893707c2b159bfad7de93f";
      };
    };
    "test-value-2.0.0" = {
      name = "test-value";
      packageName = "test-value";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/test-value/-/test-value-2.0.0.tgz";
        sha1 = "0d65c45ee0b48a757c4507a5e98ec2680a9db137";
      };
    };
    "@types/clone-0.1.29" = {
      name = "@types/clone";
      packageName = "@types/clone";
      version = "0.1.29";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/clone/-/clone-0.1.29.tgz";
        sha1 = "65a0be88189ffddcd373e450aa6b68c9c83218b7";
      };
    };
    "@types/node-4.0.30" = {
      name = "@types/node";
      packageName = "@types/node";
      version = "4.0.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-4.0.30.tgz";
        sha1 = "553f490ed3030311620f88003e7abfc0edcb301e";
      };
    };
    "@types/parse5-0.0.28" = {
      name = "@types/parse5";
      packageName = "@types/parse5";
      version = "0.0.28";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/parse5/-/parse5-0.0.28.tgz";
        sha1 = "2a38cb7145bb157688d4ad2c46944c6dffae3cc6";
      };
    };
    "clone-1.0.2" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.2.tgz";
        sha1 = "260b7a99ebb1edfe247538175f783243cb19d149";
      };
    };
    "parse5-1.5.1" = {
      name = "parse5";
      packageName = "parse5";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse5/-/parse5-1.5.1.tgz";
        sha1 = "9b7f3b0de32be78dc2401b17573ccaf0f6f59d94";
      };
    };
    "@types/node-6.0.37" = {
      name = "@types/node";
      packageName = "@types/node";
      version = "6.0.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-6.0.37.tgz";
        sha1 = "a1e081f2ec60074113d3a1fbf11f35d304f30e39";
      };
    };
    "es6-promise-2.3.0" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-2.3.0.tgz";
        sha1 = "96edb9f2fdb01995822b263dd8aadab6748181bc";
      };
    };
    "hydrolysis-1.24.1" = {
      name = "hydrolysis";
      packageName = "hydrolysis";
      version = "1.24.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/hydrolysis/-/hydrolysis-1.24.1.tgz";
        sha1 = "0f94f055d1065ac0d81ff40b762d143fef07eff4";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "path-posix-1.0.0" = {
      name = "path-posix";
      packageName = "path-posix";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-posix/-/path-posix-1.0.0.tgz";
        sha1 = "06b26113f56beab042545a23bfa88003ccac260f";
      };
    };
    "update-notifier-0.6.3" = {
      name = "update-notifier";
      packageName = "update-notifier";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-notifier/-/update-notifier-0.6.3.tgz";
        sha1 = "776dec8daa13e962a341e8a1d98354306b67ae08";
      };
    };
    "babel-polyfill-6.13.0" = {
      name = "babel-polyfill";
      packageName = "babel-polyfill";
      version = "6.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-polyfill/-/babel-polyfill-6.13.0.tgz";
        sha1 = "5978215c25d49a697eb78afc54e63c9d3a73d5ec";
      };
    };
    "doctrine-0.7.2" = {
      name = "doctrine";
      packageName = "doctrine";
      version = "0.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/doctrine/-/doctrine-0.7.2.tgz";
        sha1 = "7cb860359ba3be90e040b26b729ce4bfa654c523";
      };
    };
    "escodegen-1.8.1" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.8.1.tgz";
        sha1 = "5a5b53af4693110bebb0867aa3430dd3b70a1018";
      };
    };
    "espree-3.1.7" = {
      name = "espree";
      packageName = "espree";
      version = "3.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/espree/-/espree-3.1.7.tgz";
        sha1 = "fd5deec76a97a5120a9cd3a7cb1177a0923b11d2";
      };
    };
    "estraverse-3.1.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-3.1.0.tgz";
        sha1 = "15e28a446b8b82bc700ccc8b96c78af4da0d6cba";
      };
    };
    "path-is-absolute-1.0.0" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.0.tgz";
        sha1 = "263dada66ab3f2fb10bf7f9d24dd8f3e570ef912";
      };
    };
    "babel-runtime-6.11.6" = {
      name = "babel-runtime";
      packageName = "babel-runtime";
      version = "6.11.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.11.6.tgz";
        sha1 = "6db707fef2d49c49bfa3cb64efdb436b518b8222";
      };
    };
    "regenerator-runtime-0.9.5" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.9.5.tgz";
        sha1 = "403d6d40a4bdff9c330dd9392dcbb2d9a8bba1fc";
      };
    };
    "esutils-1.1.6" = {
      name = "esutils";
      packageName = "esutils";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-1.1.6.tgz";
        sha1 = "c01ccaa9ae4b897c6d0c3e210ae52f3c7a844375";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "estraverse-1.9.3" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-1.9.3.tgz";
        sha1 = "af67f2dc922582415950926091a4005d29c9bb44";
      };
    };
    "esutils-2.0.2" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.2.tgz";
        sha1 = "0abf4f1caa5bcb1f7a9d8acc6dea4faaa04bac9b";
      };
    };
    "esprima-2.7.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-2.7.3.tgz";
        sha1 = "96e3b70d5779f6ad49cd032673d1c312767ba581";
      };
    };
    "optionator-0.8.1" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.1.tgz";
        sha1 = "e31b4932cdd5fb862a8b0d10bc63d3ee1ec7d78b";
      };
    };
    "source-map-0.2.0" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.2.0.tgz";
        sha1 = "dab73fbcfc2ba819b4de03bd6f6eaa48164b3f9d";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "fast-levenshtein-1.1.4" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-1.1.4.tgz";
        sha1 = "e6a754cc8f15e58987aa9cbd27af66fd6f4e5af9";
      };
    };
    "acorn-3.3.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-3.3.0.tgz";
        sha1 = "45e37fb39e8da3f25baee3ff5369e2bb5f22017a";
      };
    };
    "acorn-jsx-3.0.1" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-3.0.1.tgz";
        sha1 = "afdf9488fb1ecefc8348f6fb22f464e32a58b36b";
      };
    };
    "boxen-0.3.1" = {
      name = "boxen";
      packageName = "boxen";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boxen/-/boxen-0.3.1.tgz";
        sha1 = "a7d898243ae622f7abb6bb604d740a76c6a5461b";
      };
    };
    "configstore-2.0.0" = {
      name = "configstore";
      packageName = "configstore";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/configstore/-/configstore-2.0.0.tgz";
        sha1 = "8d81e9cdfa73ebd0e06bc985147856b2f1c4e764";
      };
    };
    "is-npm-1.0.0" = {
      name = "is-npm";
      packageName = "is-npm";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-npm/-/is-npm-1.0.0.tgz";
        sha1 = "f2fb63a65e4905b406c86072765a1a4dc793b9f4";
      };
    };
    "latest-version-2.0.0" = {
      name = "latest-version";
      packageName = "latest-version";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/latest-version/-/latest-version-2.0.0.tgz";
        sha1 = "56f8d6139620847b8017f8f1f4d78e211324168b";
      };
    };
    "semver-diff-2.1.0" = {
      name = "semver-diff";
      packageName = "semver-diff";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver-diff/-/semver-diff-2.1.0.tgz";
        sha1 = "4bbb8437c8d37e4b0cf1a68fd726ec6d645d6d36";
      };
    };
    "filled-array-1.1.0" = {
      name = "filled-array";
      packageName = "filled-array";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/filled-array/-/filled-array-1.1.0.tgz";
        sha1 = "c3c4f6c663b923459a9aa29912d2d031f1507f84";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "repeating-2.0.1" = {
      name = "repeating";
      packageName = "repeating";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeating/-/repeating-2.0.1.tgz";
        sha1 = "5214c53a926d3552707527fbab415dbc08d06dda";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "widest-line-1.0.0" = {
      name = "widest-line";
      packageName = "widest-line";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/widest-line/-/widest-line-1.0.0.tgz";
        sha1 = "0c09c85c2a94683d0d7eaf8ee097d564bf0e105c";
      };
    };
    "is-finite-1.0.1" = {
      name = "is-finite";
      packageName = "is-finite";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-finite/-/is-finite-1.0.1.tgz";
        sha1 = "6438603eaebe2793948ff4a4262ec8db3d62597b";
      };
    };
    "number-is-nan-1.0.0" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.0.tgz";
        sha1 = "c020f529c5282adfdd233d91d4b181c3d686dc4b";
      };
    };
    "code-point-at-1.0.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.0.0.tgz";
        sha1 = "f69b192d3f7d91e382e4b71bddb77878619ab0c6";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "dot-prop-2.4.0" = {
      name = "dot-prop";
      packageName = "dot-prop";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dot-prop/-/dot-prop-2.4.0.tgz";
        sha1 = "848e28f7f1d50740c6747ab3cb07670462b6f89c";
      };
    };
    "os-tmpdir-1.0.1" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.1.tgz";
        sha1 = "e9b423a1edaf479882562e92ed71d7743a071b6e";
      };
    };
    "osenv-0.1.3" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.3.tgz";
        sha1 = "83cf05c6d6458fc4d5ac6362ea325d92f2754217";
      };
    };
    "uuid-2.0.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-2.0.2.tgz";
        sha1 = "48bd5698f0677e3c7901a1c46ef15b1643794726";
      };
    };
    "write-file-atomic-1.2.0" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.2.0.tgz";
        sha1 = "14c66d4e4cb3ca0565c28cf3b7a6f3e4d5938fab";
      };
    };
    "xdg-basedir-2.0.0" = {
      name = "xdg-basedir";
      packageName = "xdg-basedir";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-2.0.0.tgz";
        sha1 = "edbc903cc385fc04523d966a335504b5504d1bd2";
      };
    };
    "is-obj-1.0.1" = {
      name = "is-obj";
      packageName = "is-obj";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-obj/-/is-obj-1.0.1.tgz";
        sha1 = "3e4729ac1f5fde025cd7d83a896dab9f4f67db0f";
      };
    };
    "os-homedir-1.0.1" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.1.tgz";
        sha1 = "0d62bdf44b916fd3bbdcf2cab191948fb094f007";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "slide-1.1.6" = {
      name = "slide";
      packageName = "slide";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/slide/-/slide-1.1.6.tgz";
        sha1 = "56eb027d65b4d2dce6cb2e2d32c4d4afc9e1d707";
      };
    };
    "package-json-2.3.3" = {
      name = "package-json";
      packageName = "package-json";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json/-/package-json-2.3.3.tgz";
        sha1 = "14895311a963d18edf8801e06b67ea87795d15b9";
      };
    };
    "got-5.6.0" = {
      name = "got";
      packageName = "got";
      version = "5.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/got/-/got-5.6.0.tgz";
        sha1 = "bb1d7ee163b78082bbc8eb836f3f395004ea6fbf";
      };
    };
    "rc-1.1.6" = {
      name = "rc";
      packageName = "rc";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc/-/rc-1.1.6.tgz";
        sha1 = "43651b76b6ae53b5c802f1151fa3fc3b059969c9";
      };
    };
    "registry-url-3.1.0" = {
      name = "registry-url";
      packageName = "registry-url";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/registry-url/-/registry-url-3.1.0.tgz";
        sha1 = "3d4ef870f73dde1d77f0cf9a381432444e174942";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "create-error-class-3.0.2" = {
      name = "create-error-class";
      packageName = "create-error-class";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/create-error-class/-/create-error-class-3.0.2.tgz";
        sha1 = "06be7abef947a3f14a30fd610671d401bca8b7b6";
      };
    };
    "duplexer2-0.1.4" = {
      name = "duplexer2";
      packageName = "duplexer2";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer2/-/duplexer2-0.1.4.tgz";
        sha1 = "8b12dab878c0d69e3e7891051662a32fc6bddcc1";
      };
    };
    "is-plain-obj-1.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-1.1.0.tgz";
        sha1 = "71a50c8429dfca773c92a390a4a03b39fcd51d3e";
      };
    };
    "is-redirect-1.0.0" = {
      name = "is-redirect";
      packageName = "is-redirect";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-redirect/-/is-redirect-1.0.0.tgz";
        sha1 = "1d03dded53bd8db0f30c26e4f95d36fc7c87dc24";
      };
    };
    "is-retry-allowed-1.1.0" = {
      name = "is-retry-allowed";
      packageName = "is-retry-allowed";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-retry-allowed/-/is-retry-allowed-1.1.0.tgz";
        sha1 = "11a060568b67339444033d0125a61a20d564fb34";
      };
    };
    "is-stream-1.1.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-1.1.0.tgz";
        sha1 = "12d4a3dd4e68e0b79ceb8dbc84173ae80d91ca44";
      };
    };
    "lowercase-keys-1.0.0" = {
      name = "lowercase-keys";
      packageName = "lowercase-keys";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lowercase-keys/-/lowercase-keys-1.0.0.tgz";
        sha1 = "4e3366b39e7f5457e35f1324bdf6f88d0bfc7306";
      };
    };
    "node-status-codes-1.0.0" = {
      name = "node-status-codes";
      packageName = "node-status-codes";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-status-codes/-/node-status-codes-1.0.0.tgz";
        sha1 = "5ae5541d024645d32a58fcddc9ceecea7ae3ac2f";
      };
    };
    "parse-json-2.2.0" = {
      name = "parse-json";
      packageName = "parse-json";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-json/-/parse-json-2.2.0.tgz";
        sha1 = "f480f40434ef80741f8469099f8dea18f55a4dc9";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "read-all-stream-3.1.0" = {
      name = "read-all-stream";
      packageName = "read-all-stream";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-all-stream/-/read-all-stream-3.1.0.tgz";
        sha1 = "35c3e177f2078ef789ee4bfafa4373074eaef4fa";
      };
    };
    "readable-stream-2.1.5" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.1.5.tgz";
        sha1 = "66fa8b720e1438b364681f2ad1a63c618448c9d0";
      };
    };
    "timed-out-2.0.0" = {
      name = "timed-out";
      packageName = "timed-out";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/timed-out/-/timed-out-2.0.0.tgz";
        sha1 = "f38b0ae81d3747d628001f41dafc652ace671c0a";
      };
    };
    "unzip-response-1.0.0" = {
      name = "unzip-response";
      packageName = "unzip-response";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unzip-response/-/unzip-response-1.0.0.tgz";
        sha1 = "bfda54eeec658f00c2df4d4494b9dca0ca00f3e4";
      };
    };
    "url-parse-lax-1.0.0" = {
      name = "url-parse-lax";
      packageName = "url-parse-lax";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-parse-lax/-/url-parse-lax-1.0.0.tgz";
        sha1 = "7af8f303645e9bd79a272e7a14ac68bc0609da73";
      };
    };
    "capture-stack-trace-1.0.0" = {
      name = "capture-stack-trace";
      packageName = "capture-stack-trace";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/capture-stack-trace/-/capture-stack-trace-1.0.0.tgz";
        sha1 = "4a6fa07399c26bba47f0b2496b4d0fb408c5550d";
      };
    };
    "error-ex-1.3.0" = {
      name = "error-ex";
      packageName = "error-ex";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-ex/-/error-ex-1.3.0.tgz";
        sha1 = "e67b43f3e82c96ea3a584ffee0b9fc3325d802d9";
      };
    };
    "is-arrayish-0.2.1" = {
      name = "is-arrayish";
      packageName = "is-arrayish";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arrayish/-/is-arrayish-0.2.1.tgz";
        sha1 = "77c99840527aa8ecb1a8ba697b80645a7a926a9d";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "prepend-http-1.0.4" = {
      name = "prepend-http";
      packageName = "prepend-http";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/prepend-http/-/prepend-http-1.0.4.tgz";
        sha1 = "d4f4562b0ce3696e41ac52d0e002e57a635dc6dc";
      };
    };
    "ini-1.3.4" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.4.tgz";
        sha1 = "0537cb79daf59b59a1a517dff706c86ec039162e";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "strip-json-comments-1.0.4" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz";
        sha1 = "1e15fbcac97d3ee99bf2d73b4c656b082bbafb91";
      };
    };
    "crisper-1.2.0" = {
      name = "crisper";
      packageName = "crisper";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/crisper/-/crisper-1.2.0.tgz";
        sha1 = "9a91f597d71f6110294e076ad44dbb3408568e46";
      };
    };
    "cli-1.0.0" = {
      name = "cli";
      packageName = "cli";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cli/-/cli-1.0.0.tgz";
        sha1 = "ee07dfc1390e3f2e6a9957cf88e1d4bfa777719d";
      };
    };
    "console-browserify-1.1.0" = {
      name = "console-browserify";
      packageName = "console-browserify";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-browserify/-/console-browserify-1.1.0.tgz";
        sha1 = "f0241c45730a9fc6323b206dbf38edc741d0bb10";
      };
    };
    "htmlparser2-3.8.3" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "3.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-3.8.3.tgz";
        sha1 = "996c28b191516a8be86501a7d79757e5c70c1068";
      };
    };
    "minimatch-3.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.3.tgz";
        sha1 = "2a4e4090b96b2db06a9d7df01055a62a77c9b774";
      };
    };
    "shelljs-0.3.0" = {
      name = "shelljs";
      packageName = "shelljs";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shelljs/-/shelljs-0.3.0.tgz";
        sha1 = "3596e6307a781544f591f37da618360f31db57b1";
      };
    };
    "lodash-3.7.0" = {
      name = "lodash";
      packageName = "lodash";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-3.7.0.tgz";
        sha1 = "3678bd8ab995057c07ade836ed2ef087da811d45";
      };
    };
    "glob-7.0.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.0.6.tgz";
        sha1 = "211bafaf49e525b8cd93260d14ab136152b3f57a";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "inflight-1.0.5" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.5.tgz";
        sha1 = "db3204cd5a9de2e6cd890b85c6e2f66bcf4f620a";
      };
    };
    "once-1.3.3" = {
      name = "once";
      packageName = "once";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.3.3.tgz";
        sha1 = "b2e261557ce4c314ec8304f3fa82663e4297ca20";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.6" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.6.tgz";
        sha1 = "7197d7eaa9b87e648390ea61fc66c84427420df9";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "date-now-0.1.4" = {
      name = "date-now";
      packageName = "date-now";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-now/-/date-now-0.1.4.tgz";
        sha1 = "eaf439fd4d4848ad74e5cc7dbef200672b9e345b";
      };
    };
    "domhandler-2.3.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-2.3.0.tgz";
        sha1 = "2de59a0822d5027fabff6f032c2b25a2a8abe738";
      };
    };
    "domutils-1.5.1" = {
      name = "domutils";
      packageName = "domutils";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-1.5.1.tgz";
        sha1 = "dcd8488a26f563d61079e48c9f7b7e32373682cf";
      };
    };
    "domelementtype-1.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.3.0.tgz";
        sha1 = "b17aed82e8ab59e52dd9c19b1756e0fc187204c2";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "entities-1.0.0" = {
      name = "entities";
      packageName = "entities";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.0.0.tgz";
        sha1 = "b2987aa3821347fcde642b24fdfc9e4fb712bf26";
      };
    };
    "dom-serializer-0.1.0" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-0.1.0.tgz";
        sha1 = "073c697546ce0780ce23be4a28e293e40bc30c82";
      };
    };
    "domelementtype-1.1.3" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-1.1.3.tgz";
        sha1 = "bd28773e2642881aec51544924299c5cd822185b";
      };
    };
    "entities-1.1.1" = {
      name = "entities";
      packageName = "entities";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-1.1.1.tgz";
        sha1 = "6e5c2d0a5621b5dadaecef80b90edfb5cd7772f0";
      };
    };
  };
  args = {
    name = "rhodecode-enterprise";
    packageName = "rhodecode-enterprise";
    version = "0.0.1";
    src = ./.;
    dependencies = [
      sources."grunt-0.4.5"
      sources."grunt-contrib-copy-1.0.0"
      (sources."grunt-contrib-concat-0.5.1" // {
        dependencies = [
          sources."chalk-0.5.1"
          sources."ansi-styles-1.1.0"
          sources."has-ansi-0.1.0"
          sources."strip-ansi-0.3.0"
          sources."supports-color-0.2.0"
          sources."ansi-regex-0.2.1"
        ];
      })
      sources."grunt-contrib-jshint-0.12.0"
      (sources."grunt-contrib-less-1.4.0" // {
        dependencies = [
          sources."async-2.0.1"
          sources."lodash-4.15.0"
        ];
      })
      (sources."grunt-contrib-watch-0.6.1" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."async-0.2.10"
        ];
      })
      sources."crisper-2.0.2"
      (sources."vulcanize-1.14.8" // {
        dependencies = [
          sources."nopt-3.0.6"
        ];
      })
      sources."grunt-crisper-1.0.1"
      (sources."grunt-vulcanize-1.0.0" // {
        dependencies = [
          sources."crisper-1.2.0"
          sources."nopt-3.0.6"
        ];
      })
      (sources."jshint-2.9.3" // {
        dependencies = [
          sources."minimatch-3.0.3"
          sources."lodash-3.7.0"
        ];
      })
      sources."async-0.1.22"
      sources."coffee-script-1.3.3"
      sources."colors-0.6.2"
      sources."dateformat-1.0.2-1.2.3"
      sources."eventemitter2-0.4.14"
      (sources."findup-sync-0.1.3" // {
        dependencies = [
          sources."glob-3.2.11"
          sources."lodash-2.4.2"
          sources."minimatch-0.3.0"
        ];
      })
      (sources."glob-3.1.21" // {
        dependencies = [
          sources."inherits-1.0.2"
        ];
      })
      sources."hooker-0.2.3"
      sources."iconv-lite-0.2.11"
      sources."minimatch-0.2.14"
      sources."nopt-1.0.10"
      sources."rimraf-2.2.8"
      sources."lodash-0.9.2"
      sources."underscore.string-2.2.1"
      sources."which-1.0.9"
      sources."js-yaml-2.0.5"
      sources."exit-0.1.2"
      sources."getobject-0.1.0"
      sources."grunt-legacy-util-0.2.0"
      (sources."grunt-legacy-log-0.1.3" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."underscore.string-2.3.3"
        ];
      })
      sources."inherits-2.0.1"
      sources."lru-cache-2.7.3"
      sources."sigmund-1.0.1"
      sources."graceful-fs-1.2.3"
      sources."abbrev-1.0.9"
      (sources."argparse-0.1.16" // {
        dependencies = [
          sources."underscore.string-2.4.0"
        ];
      })
      sources."esprima-1.0.4"
      sources."underscore-1.7.0"
      (sources."grunt-legacy-log-utils-0.1.1" // {
        dependencies = [
          sources."lodash-2.4.2"
          sources."underscore.string-2.3.3"
        ];
      })
      sources."chalk-1.1.3"
      sources."file-sync-cmp-0.1.1"
      sources."ansi-styles-2.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."ansi-regex-2.0.0"
      sources."source-map-0.3.0"
      sources."amdefine-1.0.0"
      (sources."less-2.7.1" // {
        dependencies = [
          sources."graceful-fs-4.1.6"
          sources."source-map-0.5.6"
        ];
      })
      sources."errno-0.1.4"
      sources."image-size-0.5.0"
      sources."mime-1.3.4"
      sources."mkdirp-0.5.1"
      sources."promise-7.1.1"
      sources."prr-0.0.0"
      sources."minimist-0.0.8"
      sources."asap-2.0.4"
      sources."gaze-0.5.2"
      sources."tiny-lr-fork-0.0.5"
      (sources."globule-0.1.0" // {
        dependencies = [
          sources."lodash-1.0.2"
        ];
      })
      sources."qs-0.5.6"
      sources."faye-websocket-0.4.4"
      (sources."noptify-0.0.3" // {
        dependencies = [
          sources."nopt-2.0.0"
        ];
      })
      sources."debug-0.7.4"
      sources."command-line-args-2.1.6"
      sources."dom5-1.3.3"
      sources."array-back-1.0.3"
      sources."command-line-usage-2.0.5"
      sources."core-js-2.4.1"
      sources."feature-detect-es6-1.3.1"
      (sources."find-replace-1.0.2" // {
        dependencies = [
          sources."test-value-2.0.0"
        ];
      })
      sources."typical-2.5.0"
      sources."ansi-escape-sequences-2.2.2"
      sources."column-layout-2.1.4"
      sources."wordwrapjs-1.2.1"
      sources."collect-all-0.2.1"
      sources."stream-connect-1.0.2"
      sources."stream-via-0.1.1"
      (sources."collect-json-1.0.8" // {
        dependencies = [
          sources."collect-all-1.0.2"
          sources."stream-via-1.0.3"
        ];
      })
      sources."deep-extend-0.4.1"
      sources."object-tools-2.0.6"
      sources."object-get-2.1.0"
      sources."test-value-1.1.0"
      sources."@types/clone-0.1.29"
      sources."@types/node-4.0.30"
      (sources."@types/parse5-0.0.28" // {
        dependencies = [
          sources."@types/node-6.0.37"
        ];
      })
      sources."clone-1.0.2"
      sources."parse5-1.5.1"
      sources."es6-promise-2.3.0"
      sources."hydrolysis-1.24.1"
      sources."path-posix-1.0.0"
      sources."update-notifier-0.6.3"
      sources."babel-polyfill-6.13.0"
      sources."doctrine-0.7.2"
      (sources."escodegen-1.8.1" // {
        dependencies = [
          sources."estraverse-1.9.3"
          sources."esutils-2.0.2"
          sources."esprima-2.7.3"
          sources."source-map-0.2.0"
        ];
      })
      sources."espree-3.1.7"
      sources."estraverse-3.1.0"
      sources."path-is-absolute-1.0.0"
      sources."babel-runtime-6.11.6"
      sources."regenerator-runtime-0.9.5"
      sources."esutils-1.1.6"
      sources."isarray-0.0.1"
      sources."optionator-0.8.1"
      sources."prelude-ls-1.1.2"
      sources."deep-is-0.1.3"
      sources."wordwrap-1.0.0"
      sources."type-check-0.3.2"
      sources."levn-0.3.0"
      sources."fast-levenshtein-1.1.4"
      sources."acorn-3.3.0"
      sources."acorn-jsx-3.0.1"
      sources."boxen-0.3.1"
      (sources."configstore-2.0.0" // {
        dependencies = [
          sources."graceful-fs-4.1.6"
        ];
      })
      sources."is-npm-1.0.0"
      sources."latest-version-2.0.0"
      sources."semver-diff-2.1.0"
      sources."filled-array-1.1.0"
      sources."object-assign-4.1.0"
      sources."repeating-2.0.1"
      sources."string-width-1.0.2"
      sources."widest-line-1.0.0"
      sources."is-finite-1.0.1"
      sources."number-is-nan-1.0.0"
      sources."code-point-at-1.0.0"
      sources."is-fullwidth-code-point-1.0.0"
      sources."dot-prop-2.4.0"
      sources."os-tmpdir-1.0.1"
      sources."osenv-0.1.3"
      sources."uuid-2.0.2"
      (sources."write-file-atomic-1.2.0" // {
        dependencies = [
          sources."graceful-fs-4.1.6"
        ];
      })
      sources."xdg-basedir-2.0.0"
      sources."is-obj-1.0.1"
      sources."os-homedir-1.0.1"
      sources."imurmurhash-0.1.4"
      sources."slide-1.1.6"
      sources."package-json-2.3.3"
      sources."got-5.6.0"
      (sources."rc-1.1.6" // {
        dependencies = [
          sources."minimist-1.2.0"
        ];
      })
      sources."registry-url-3.1.0"
      sources."semver-5.3.0"
      sources."create-error-class-3.0.2"
      sources."duplexer2-0.1.4"
      sources."is-plain-obj-1.1.0"
      sources."is-redirect-1.0.0"
      sources."is-retry-allowed-1.1.0"
      sources."is-stream-1.1.0"
      sources."lowercase-keys-1.0.0"
      sources."node-status-codes-1.0.0"
      sources."parse-json-2.2.0"
      sources."pinkie-promise-2.0.1"
      sources."read-all-stream-3.1.0"
      (sources."readable-stream-2.1.5" // {
        dependencies = [
          sources."isarray-1.0.0"
        ];
      })
      sources."timed-out-2.0.0"
      sources."unzip-response-1.0.0"
      sources."url-parse-lax-1.0.0"
      sources."capture-stack-trace-1.0.0"
      sources."error-ex-1.3.0"
      sources."is-arrayish-0.2.1"
      sources."pinkie-2.0.4"
      sources."buffer-shims-1.0.0"
      sources."core-util-is-1.0.2"
      sources."process-nextick-args-1.0.7"
      sources."string_decoder-0.10.31"
      sources."util-deprecate-1.0.2"
      sources."prepend-http-1.0.4"
      sources."ini-1.3.4"
      sources."strip-json-comments-1.0.4"
      (sources."cli-1.0.0" // {
        dependencies = [
          sources."glob-7.0.6"
          sources."minimatch-3.0.3"
        ];
      })
      sources."console-browserify-1.1.0"
      (sources."htmlparser2-3.8.3" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      sources."shelljs-0.3.0"
      sources."fs.realpath-1.0.0"
      sources."inflight-1.0.5"
      sources."once-1.3.3"
      sources."wrappy-1.0.2"
      sources."brace-expansion-1.1.6"
      sources."balanced-match-0.4.2"
      sources."concat-map-0.0.1"
      sources."date-now-0.1.4"
      sources."domhandler-2.3.0"
      sources."domutils-1.5.1"
      sources."domelementtype-1.3.0"
      sources."entities-1.0.0"
      (sources."dom-serializer-0.1.0" // {
        dependencies = [
          sources."domelementtype-1.1.3"
          sources."entities-1.1.1"
        ];
      })
    ];
    meta = {
    };
    production = false;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}